#!/usr/bin/env node
// GPUscale sizing CLI · GENERATED by tools/build_skill.py — do not edit by hand
// engine v27 · library v35 · studio 5.34.2 · same math and libraries as https://gpuscale.net · MIT
'use strict';

const META = {"library": "v35", "engine": 27, "studio": "5.34.2", "updated": "2026-07-31"};
const MODELS = [
{"name": "Llama 3.1 8B", "params": 8, "active": 8, "hidden": 4096, "layers": 32, "kvHeads": 8, "headDim": 128, "ctx": 131072, "experts": null, "activeExperts": null, "arch": "Dense (GQA)", "dev": "Meta", "url": "https://ai.meta.com/blog/meta-llama-3-1/"},
{"name": "Llama 3.1 70B", "params": 70, "active": 70, "hidden": 8192, "layers": 80, "kvHeads": 8, "headDim": 128, "ctx": 131072, "experts": null, "activeExperts": null, "arch": "Dense (GQA)", "dev": "Meta", "url": "https://ai.meta.com/blog/meta-llama-3-1/"},
{"name": "Llama 3.1 405B", "params": 405, "active": 405, "hidden": 16384, "layers": 126, "kvHeads": 8, "headDim": 128, "ctx": 131072, "experts": null, "activeExperts": null, "arch": "Dense (GQA)", "dev": "Meta", "url": "https://ai.meta.com/blog/meta-llama-3-1/"},
{"name": "Llama 4 Scout 109B (MoE)", "params": 109, "active": 17, "hidden": 5120, "layers": 48, "kvHeads": 8, "headDim": 128, "ctx": 10485760, "experts": 16, "activeExperts": 1, "arch": "MoE (16E/1A; iRoPE: 36 chunked local 8192 + 12 NoPE global)", "dev": "Meta", "url": "https://ai.meta.com/blog/llama-4-multimodal-intelligence/", "kvGlobal": 12, "kvWin": 8192},
{"name": "Llama 4 Maverick 400B (MoE)", "params": 400, "active": 17, "hidden": 5120, "layers": 48, "kvHeads": 8, "headDim": 128, "ctx": 1048576, "experts": 128, "activeExperts": 2, "arch": "MoE (128E/2A; iRoPE: 36 chunked local 8192 + 12 NoPE global)", "dev": "Meta", "url": "https://ai.meta.com/blog/llama-4-multimodal-intelligence/", "kvGlobal": 12, "kvWin": 8192},
{"name": "Qwen3 0.6B", "params": 0.6, "active": 0.6, "hidden": 1024, "layers": 28, "kvHeads": 8, "headDim": 128, "ctx": 32768, "experts": null, "activeExperts": null, "arch": "Dense (GQA)", "dev": "Alibaba Cloud", "url": "https://qwenlm.github.io/blog/qwen3/"},
{"name": "Qwen3 1.7B", "params": 1.7, "active": 1.7, "hidden": 2048, "layers": 28, "kvHeads": 8, "headDim": 128, "ctx": 32768, "experts": null, "activeExperts": null, "arch": "Dense (GQA)", "dev": "Alibaba Cloud", "url": "https://qwenlm.github.io/blog/qwen3/"},
{"name": "Qwen3 4B", "params": 4, "active": 4, "hidden": 2560, "layers": 36, "kvHeads": 8, "headDim": 128, "ctx": 32768, "experts": null, "activeExperts": null, "arch": "Dense (GQA)", "dev": "Alibaba Cloud", "url": "https://qwenlm.github.io/blog/qwen3/"},
{"name": "Qwen3 8B", "params": 8, "active": 8, "hidden": 4096, "layers": 36, "kvHeads": 8, "headDim": 128, "ctx": 131072, "experts": null, "activeExperts": null, "arch": "Dense (GQA)", "dev": "Alibaba Cloud", "url": "https://qwenlm.github.io/blog/qwen3/"},
{"name": "Qwen3 14B", "params": 14, "active": 14, "hidden": 5120, "layers": 40, "kvHeads": 8, "headDim": 128, "ctx": 131072, "experts": null, "activeExperts": null, "arch": "Dense (GQA)", "dev": "Alibaba Cloud", "url": "https://qwenlm.github.io/blog/qwen3/"},
{"name": "Qwen3 32B", "params": 32, "active": 32, "hidden": 5120, "layers": 64, "kvHeads": 8, "headDim": 128, "ctx": 131072, "experts": null, "activeExperts": null, "arch": "Dense (GQA)", "dev": "Alibaba Cloud", "url": "https://qwenlm.github.io/blog/qwen3/"},
{"name": "Qwen3 30B-A3B (MoE)", "params": 30, "active": 3, "hidden": 2048, "layers": 48, "kvHeads": 4, "headDim": 128, "ctx": 131072, "experts": 128, "activeExperts": 8, "arch": "MoE (128E/8A)", "dev": "Alibaba Cloud", "url": "https://qwenlm.github.io/blog/qwen3/"},
{"name": "Qwen3 235B-A22B (MoE)", "params": 235, "active": 22, "hidden": 4096, "layers": 94, "kvHeads": 4, "headDim": 128, "ctx": 262144, "experts": 128, "activeExperts": 8, "arch": "MoE (128E/8A)", "dev": "Alibaba Cloud", "url": "https://qwenlm.github.io/blog/qwen3/"},
{"name": "Qwen3.5 0.8B", "params": 0.8, "active": 0.8, "hidden": 1024, "layers": 24, "kvHeads": 2, "headDim": 64, "ctx": 262144, "experts": null, "activeExperts": null, "arch": "Dense (hybrid: only full-attn layers cache)", "dev": "Alibaba Cloud", "url": "https://github.com/QwenLM/Qwen3.5"},
{"name": "Qwen3.5 2B", "params": 2, "active": 2, "hidden": 2048, "layers": 24, "kvHeads": 2, "headDim": 64, "ctx": 262144, "experts": null, "activeExperts": null, "arch": "Dense (hybrid: only full-attn layers cache)", "dev": "Alibaba Cloud", "url": "https://github.com/QwenLM/Qwen3.5"},
{"name": "Qwen3.5 4B", "params": 4, "active": 4, "hidden": 2560, "layers": 32, "kvHeads": 4, "headDim": 64, "ctx": 262144, "experts": null, "activeExperts": null, "arch": "Dense (hybrid: only full-attn layers cache)", "dev": "Alibaba Cloud", "url": "https://github.com/QwenLM/Qwen3.5"},
{"name": "Qwen3.5 9B", "params": 9, "active": 9, "hidden": 4096, "layers": 32, "kvHeads": 4, "headDim": 64, "ctx": 262144, "experts": null, "activeExperts": null, "arch": "Dense (hybrid: only full-attn layers cache)", "dev": "Alibaba Cloud", "url": "https://github.com/QwenLM/Qwen3.5"},
{"name": "Qwen3.5 27B", "params": 27, "active": 27, "hidden": 5120, "layers": 64, "kvHeads": 4, "headDim": 64, "ctx": 262144, "experts": null, "activeExperts": null, "arch": "Dense (hybrid: only full-attn layers cache)", "dev": "Alibaba Cloud", "url": "https://github.com/QwenLM/Qwen3.5"},
{"name": "Qwen3.5 35B-A3B (MoE)", "params": 35, "active": 3, "hidden": 2048, "layers": 40, "kvHeads": 2, "headDim": 64, "ctx": 262144, "experts": 256, "activeExperts": 8, "arch": "MoE (256E/8A, hybrid: only full-attn layers cache)", "dev": "Alibaba Cloud", "url": "https://github.com/QwenLM/Qwen3.5"},
{"name": "Qwen3.5 122B-A10B (MoE)", "params": 122, "active": 10, "hidden": 3072, "layers": 48, "kvHeads": 2, "headDim": 64, "ctx": 262144, "experts": 256, "activeExperts": 8, "arch": "MoE (256E/8A, hybrid: only full-attn layers cache)", "dev": "Alibaba Cloud", "url": "https://github.com/QwenLM/Qwen3.5"},
{"name": "Qwen3.5 397B-A17B (MoE)", "params": 397, "active": 17, "hidden": 4096, "layers": 60, "kvHeads": 2, "headDim": 64, "ctx": 262144, "experts": 512, "activeExperts": 10, "arch": "MoE (512E/10A, hybrid: only full-attn layers cache)", "dev": "Alibaba Cloud", "url": "https://github.com/QwenLM/Qwen3.5"},
{"name": "DeepSeek-V3 671B (MoE)", "params": 671, "active": 37, "hidden": 7168, "layers": 61, "kvHeads": 1, "headDim": 288, "ctx": 131072, "experts": 257, "activeExperts": 9, "arch": "MoE (257E/9A, MLA eff.)", "dev": "DeepSeek", "url": "https://huggingface.co/deepseek-ai/DeepSeek-V3"},
{"name": "DeepSeek-R1 671B (MoE)", "params": 671, "active": 37, "hidden": 7168, "layers": 61, "kvHeads": 1, "headDim": 288, "ctx": 131072, "experts": 257, "activeExperts": 9, "arch": "MoE (257E/9A, MLA eff.)", "dev": "DeepSeek", "url": "https://huggingface.co/deepseek-ai/DeepSeek-R1"},
{"name": "Kimi K2 1T-A32B (MoE)", "params": 1000, "active": 32, "hidden": 7168, "layers": 61, "kvHeads": 1, "headDim": 288, "ctx": 131072, "experts": 385, "activeExperts": 9, "arch": "MoE (385E/9A, MLA eff.)", "dev": "Moonshot AI", "url": "https://huggingface.co/moonshotai/Kimi-K2-Instruct"},
{"name": "Kimi K2.5 1T-A32B (MoE)", "params": 1000, "active": 32, "hidden": 7168, "layers": 61, "kvHeads": 1, "headDim": 288, "ctx": 262144, "experts": 385, "activeExperts": 9, "arch": "MoE (385E/9A, MLA eff.)", "dev": "Moonshot AI", "url": "https://huggingface.co/moonshotai/Kimi-K2.5"},
{"name": "Mistral 7B v0.3", "params": 7.3, "active": 7.3, "hidden": 4096, "layers": 32, "kvHeads": 8, "headDim": 128, "ctx": 32768, "experts": null, "activeExperts": null, "arch": "Dense (GQA)", "dev": "Mistral AI", "url": "https://huggingface.co/mistralai/Mistral-7B-v0.3"},
{"name": "Mixtral 8x7B (MoE)", "params": 46.7, "active": 12.9, "hidden": 4096, "layers": 32, "kvHeads": 8, "headDim": 128, "ctx": 32768, "experts": 8, "activeExperts": 2, "arch": "MoE (8E/2A)", "dev": "Mistral AI", "url": "https://huggingface.co/mistralai/Mixtral-8x7B-Instruct-v0.1"},
{"name": "Mistral Small 3 24B", "params": 24, "active": 24, "hidden": 5120, "layers": 40, "kvHeads": 8, "headDim": 128, "ctx": 32768, "experts": null, "activeExperts": null, "arch": "Dense (GQA)", "dev": "Mistral AI", "url": "https://mistral.ai/news/mistral-small-3"},
{"name": "Mistral Small 3.1 24B", "params": 24, "active": 24, "hidden": 5120, "layers": 40, "kvHeads": 8, "headDim": 128, "ctx": 131072, "experts": null, "activeExperts": null, "arch": "Dense (GQA)", "dev": "Mistral AI", "url": "https://mistral.ai/news/mistral-small-3-1"},
{"name": "Mistral Large 3 675B (MoE)", "params": 675, "active": 41, "hidden": 12288, "layers": 88, "kvHeads": 8, "headDim": 128, "ctx": 262144, "experts": null, "activeExperts": null, "arch": "MoE (granular; cfg approx)", "dev": "Mistral AI", "url": "https://mistral.ai/news/mistral-3"},
{"name": "Mixtral 8x22B (MoE)", "params": 141, "active": 39, "hidden": 6144, "layers": 56, "kvHeads": 8, "headDim": 128, "ctx": 65536, "experts": 8, "activeExperts": 2, "arch": "MoE (8E/2A)", "dev": "Mistral AI", "url": "https://huggingface.co/mistralai/Mixtral-8x22B-v0.1"},
{"name": "Gemma 2 2B", "params": 2, "active": 2, "hidden": 2304, "layers": 26, "kvHeads": 4, "headDim": 256, "ctx": 8192, "experts": null, "activeExperts": null, "arch": "Dense (GQA + SWA 1:1, win 4096)", "dev": "Google", "url": "https://ai.google.dev/gemma/docs/core/model_card_2", "kvGlobal": 13, "kvWin": 4096},
{"name": "Gemma 2 9B", "params": 9, "active": 9, "hidden": 3584, "layers": 42, "kvHeads": 8, "headDim": 256, "ctx": 8192, "experts": null, "activeExperts": null, "arch": "Dense (GQA + SWA 1:1, win 4096)", "dev": "Google", "url": "https://ai.google.dev/gemma/docs/core/model_card_2", "kvGlobal": 21, "kvWin": 4096},
{"name": "Gemma 2 27B", "params": 27, "active": 27, "hidden": 4608, "layers": 46, "kvHeads": 16, "headDim": 128, "ctx": 8192, "experts": null, "activeExperts": null, "arch": "Dense (GQA + SWA 1:1, win 4096)", "dev": "Google", "url": "https://ai.google.dev/gemma/docs/core/model_card_2", "kvGlobal": 23, "kvWin": 4096},
{"name": "Gemma 3 1B", "params": 1, "active": 1, "hidden": 1152, "layers": 26, "kvHeads": 1, "headDim": 256, "ctx": 32768, "experts": null, "activeExperts": null, "arch": "Dense (GQA + SWA 5:1, win 512)", "dev": "Google", "url": "https://ai.google.dev/gemma/docs/core/model_card_3", "kvGlobal": 4, "kvWin": 512},
{"name": "Gemma 3 4B", "params": 4.3, "active": 4.3, "hidden": 2560, "layers": 34, "kvHeads": 4, "headDim": 256, "ctx": 131072, "experts": null, "activeExperts": null, "arch": "Dense (GQA + SWA 5:1, win 1024)", "dev": "Google", "url": "https://ai.google.dev/gemma/docs/core/model_card_3", "kvGlobal": 5, "kvWin": 1024},
{"name": "Gemma 3 12B", "params": 12.2, "active": 12.2, "hidden": 3840, "layers": 48, "kvHeads": 8, "headDim": 256, "ctx": 131072, "experts": null, "activeExperts": null, "arch": "Dense (GQA + SWA 5:1, win 1024)", "dev": "Google", "url": "https://ai.google.dev/gemma/docs/core/model_card_3", "kvGlobal": 8, "kvWin": 1024},
{"name": "Gemma 3 27B", "params": 27.4, "active": 27.4, "hidden": 5376, "layers": 62, "kvHeads": 16, "headDim": 128, "ctx": 131072, "experts": null, "activeExperts": null, "arch": "Dense (GQA + SWA 5:1, win 1024)", "dev": "Google", "url": "https://ai.google.dev/gemma/docs/core/model_card_3", "kvGlobal": 10, "kvWin": 1024},
{"name": "Gemma 4 E2B", "params": 5.1, "active": 2.3, "hidden": 1536, "layers": 35, "kvHeads": 1, "headDim": 256, "ctx": 131072, "experts": null, "activeExperts": null, "arch": "Dense (SWA 4:1 win 512; KV shared over last 20 of 35)", "dev": "Google", "url": "https://ai.google.dev/gemma/docs/core/model_card_4", "kvGlobal": 3, "kvWin": 512, "kvgHeads": 1, "kvgDim": 512, "kvLayers": 15},
{"name": "Gemma 4 E4B", "params": 8, "active": 4.5, "hidden": 2560, "layers": 42, "kvHeads": 2, "headDim": 256, "ctx": 131072, "experts": null, "activeExperts": null, "arch": "Dense (SWA 5:1 win 512; KV shared over last 18 of 42)", "dev": "Google", "url": "https://ai.google.dev/gemma/docs/core/model_card_4", "kvGlobal": 4, "kvWin": 512, "kvgHeads": 2, "kvgDim": 512, "kvLayers": 24},
{"name": "Gemma 4 26B-A4B (MoE)", "params": 25.2, "active": 3.8, "hidden": 2816, "layers": 30, "kvHeads": 8, "headDim": 256, "ctx": 262144, "experts": 129, "activeExperts": 9, "arch": "MoE (128E/8A; SWA 5:1 win 1024; global v=k, 2 kv x 512)", "dev": "Google", "url": "https://ai.google.dev/gemma/docs/core/model_card_4", "kvGlobal": 5, "kvWin": 1024, "kvgHeads": 2, "kvgDim": 512, "kvgKeyOnly": true},
{"name": "Gemma 4 31B", "params": 30.7, "active": 30.7, "hidden": 5376, "layers": 60, "kvHeads": 16, "headDim": 256, "ctx": 262144, "experts": null, "activeExperts": null, "arch": "Dense (SWA 5:1 win 1024; global v=k, 4 kv x 512)", "dev": "Google", "url": "https://ai.google.dev/gemma/docs/core/model_card_4", "kvGlobal": 10, "kvWin": 1024, "kvgHeads": 4, "kvgDim": 512, "kvgKeyOnly": true},
{"name": "Phi-4-mini 3.8B", "params": 3.8, "active": 3.8, "hidden": 3072, "layers": 32, "kvHeads": 8, "headDim": 128, "ctx": 131072, "experts": null, "activeExperts": null, "arch": "Dense (GQA)", "dev": "Microsoft", "url": "https://huggingface.co/microsoft/Phi-4-mini-instruct"},
{"name": "Phi-4 14B", "params": 14, "active": 14, "hidden": 5120, "layers": 40, "kvHeads": 10, "headDim": 128, "ctx": 16384, "experts": null, "activeExperts": null, "arch": "Dense (GQA)", "dev": "Microsoft", "url": "https://huggingface.co/microsoft/phi-4"},
{"name": "GPT-OSS 20B", "params": 21, "active": 3.6, "hidden": 2880, "layers": 24, "kvHeads": 8, "headDim": 64, "ctx": 131072, "experts": 32, "activeExperts": 4, "arch": "MoE (32E/4A; GQA, banded SWA 1:1 win 128)", "dev": "OpenAI", "url": "https://openai.com/index/gpt-oss-model-card/", "kvGlobal": 12, "kvWin": 128},
{"name": "GPT-OSS 120B", "params": 117, "active": 5.1, "hidden": 2880, "layers": 36, "kvHeads": 8, "headDim": 64, "ctx": 131072, "experts": 128, "activeExperts": 4, "arch": "MoE (128E/4A; GQA, banded SWA 1:1 win 128)", "dev": "OpenAI", "url": "https://openai.com/index/gpt-oss-model-card/", "kvGlobal": 18, "kvWin": 128},
{"name": "Qwen3-Next 80B-A3B (MoE, hybrid)", "params": 80, "active": 3.9, "hidden": 2048, "layers": 48, "kvHeads": 2, "headDim": 64, "ctx": 262144, "experts": 512, "activeExperts": 10, "arch": "MoE (512E/10A, hybrid attn)", "dev": "Alibaba", "url": "https://huggingface.co/Qwen/Qwen3-Next-80B-A3B-Instruct"},
{"name": "Qwen3-Coder 480B-A35B (MoE)", "params": 480, "active": 35, "hidden": 6144, "layers": 62, "kvHeads": 8, "headDim": 128, "ctx": 262144, "experts": 160, "activeExperts": 8, "arch": "MoE (160E/8A, GQA)", "dev": "Alibaba", "url": "https://huggingface.co/Qwen/Qwen3-Coder-480B-A35B-Instruct"},
{"name": "DeepSeek-V3.1 671B (MoE)", "params": 671, "active": 37, "hidden": 7168, "layers": 61, "kvHeads": 1, "headDim": 288, "ctx": 131072, "experts": 257, "activeExperts": 9, "arch": "MoE (257E/9A, MLA eff.)", "dev": "DeepSeek", "url": "https://huggingface.co/deepseek-ai/DeepSeek-V3.1"},
{"name": "DeepSeek-V3.2 671B (MoE, DSA)", "params": 671, "active": 37, "hidden": 7168, "layers": 61, "kvHeads": 1, "headDim": 288, "ctx": 131072, "experts": 257, "activeExperts": 9, "arch": "MoE (DSA sparse attn, MLA eff.)", "dev": "DeepSeek", "url": "https://huggingface.co/deepseek-ai/DeepSeek-V3.2"},
{"name": "GLM-4.5 355B-A32B (MoE)", "params": 355, "active": 32, "hidden": 5120, "layers": 92, "kvHeads": 8, "headDim": 128, "ctx": 131072, "experts": 160, "activeExperts": 8, "arch": "MoE (160E/8A, GQA)", "dev": "Z.ai (Zhipu)", "url": "https://huggingface.co/zai-org/GLM-4.5"},
{"name": "GLM-4.6 357B-A32B (MoE)", "params": 357, "active": 32, "hidden": 5120, "layers": 92, "kvHeads": 8, "headDim": 128, "ctx": 200000, "experts": 160, "activeExperts": 8, "arch": "MoE (160E/8A, GQA)", "dev": "Z.ai (Zhipu)", "url": "https://huggingface.co/zai-org/GLM-4.6"},
{"name": "MiniMax-M2 230B-A10B (MoE)", "params": 230, "active": 10, "hidden": 3072, "layers": 62, "kvHeads": 8, "headDim": 128, "ctx": 200000, "experts": 256, "activeExperts": 8, "arch": "MoE (256E/8A, GQA)", "dev": "MiniMax", "url": "https://huggingface.co/MiniMaxAI/MiniMax-M2"},
{"name": "Llama 3.3 70B Instruct", "params": 70, "active": 70, "hidden": 8192, "layers": 80, "kvHeads": 8, "headDim": 128, "ctx": 131072, "experts": null, "activeExperts": null, "arch": "Dense (GQA)", "dev": "Meta", "url": "https://huggingface.co/meta-llama/Llama-3.3-70B-Instruct"},
{"name": "Mistral Medium 3.5 128B", "params": 128, "active": 128, "hidden": 12288, "layers": 80, "kvHeads": 8, "headDim": 128, "ctx": 262144, "experts": null, "activeExperts": null, "arch": "Dense (GQA, est. cfg)", "dev": "Mistral AI", "url": "https://huggingface.co/mistralai/Mistral-Medium-3.5-128B"},
{"name": "Cohere Command A 111B", "params": 111, "active": 111, "hidden": 12288, "layers": 64, "kvHeads": 8, "headDim": 128, "ctx": 262144, "experts": null, "activeExperts": null, "arch": "Dense (GQA + SWA 3:1, win 4096)", "dev": "Cohere", "url": "https://huggingface.co/CohereLabs/c4ai-command-a-03-2025", "kvGlobal": 16, "kvWin": 4096},
{"name": "Ministral 3 14B", "params": 14, "active": 14, "hidden": 5120, "layers": 40, "kvHeads": 8, "headDim": 128, "ctx": 32768, "experts": null, "activeExperts": null, "arch": "Dense (GQA)", "dev": "Mistral AI", "url": "https://huggingface.co/collections/mistralai/ministral-3"},
{"name": "DeepSeek-V4-Pro 1.6T-A49B (MoE)", "params": 1600, "active": 49, "hidden": 7168, "layers": 61, "kvHeads": 1, "headDim": 40, "ctx": 1048576, "experts": 385, "activeExperts": 7, "arch": "MoE (385E/7A, hybrid CSA/HCA eff.)", "dev": "DeepSeek", "url": "https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro"},
{"name": "DeepSeek-V4-Flash 284B-A13B (MoE)", "params": 284, "active": 13, "hidden": 4096, "layers": 43, "kvHeads": 1, "headDim": 40, "ctx": 1048576, "experts": 257, "activeExperts": 7, "arch": "MoE (257E/7A, hybrid CSA/HCA eff.)", "dev": "DeepSeek", "url": "https://huggingface.co/deepseek-ai/DeepSeek-V4-Flash"},
{"name": "Kimi K2.6 1T-A32B (MoE)", "params": 1000, "active": 32, "hidden": 7168, "layers": 61, "kvHeads": 1, "headDim": 288, "ctx": 262144, "experts": 385, "activeExperts": 9, "arch": "MoE (385E/9A, MLA eff.)", "dev": "Moonshot AI", "url": "https://huggingface.co/moonshotai/Kimi-K2.6"},
{"name": "GLM-5.2 744B-A40B (MoE)", "params": 744, "active": 40, "hidden": 6144, "layers": 78, "kvHeads": 1, "headDim": 288, "ctx": 1048576, "experts": 257, "activeExperts": 9, "arch": "MoE (257E/9A, MLA+DSA eff.)", "dev": "Z.ai (Zhipu)", "url": "https://huggingface.co/zai-org/GLM-5.2"},
{"name": "MiniMax-M3 230B-A10B (MoE)", "params": 230, "active": 10, "hidden": 3072, "layers": 62, "kvHeads": 8, "headDim": 128, "ctx": 1048576, "experts": 256, "activeExperts": 8, "arch": "MoE (256E/8A, MSA sparse; cfg approx)", "dev": "MiniMax", "url": "https://huggingface.co/MiniMaxAI/MiniMax-M3"},
{"name": "Qwen3.6 35B-A3B (MoE)", "params": 35, "active": 3, "hidden": 2048, "layers": 40, "kvHeads": 2, "headDim": 256, "ctx": 262144, "experts": 256, "activeExperts": 8, "arch": "MoE (256E/8A, hybrid; cfg approx)", "dev": "Alibaba Cloud", "url": "https://huggingface.co/Qwen"},
{"name": "Nemotron 3 Super 120B-A12B (MoE)", "params": 120, "active": 12, "hidden": 6144, "layers": 52, "kvHeads": 2, "headDim": 128, "ctx": 1048576, "experts": null, "activeExperts": null, "arch": "MoE hybrid Mamba-Attn (est. cfg)", "dev": "NVIDIA", "url": "https://huggingface.co/nvidia"},
{"name": "Nemotron 3 Ultra 550B-A55B (MoE)", "params": 550, "active": 55, "hidden": 8192, "layers": 64, "kvHeads": 2, "headDim": 128, "ctx": 1048576, "experts": null, "activeExperts": null, "arch": "MoE hybrid Mamba+LatentMoE (est. cfg)", "dev": "NVIDIA", "url": "https://huggingface.co/nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B-BF16"},
{"name": "Falcon-H1-34B", "params": 34, "active": 34, "hidden": 5120, "layers": 72, "kvHeads": 4, "headDim": 128, "ctx": 262144, "experts": null, "activeExperts": null, "arch": "Dense hybrid Attn+SSM (GQA-4)", "dev": "TII (UAE)", "url": "https://huggingface.co/tiiuae/Falcon-H1-34B-Instruct"},
{"name": "Falcon3-10B", "params": 10, "active": 10, "hidden": 3072, "layers": 40, "kvHeads": 4, "headDim": 256, "ctx": 32768, "experts": null, "activeExperts": null, "arch": "Dense (GQA)", "dev": "TII (UAE)", "url": "https://huggingface.co/tiiuae/Falcon3-10B-Instruct"},
{"name": "Jais-family-30B (Arabic, 16K)", "params": 30, "active": 30, "hidden": 7168, "layers": 48, "kvHeads": 56, "headDim": 128, "ctx": 16384, "experts": null, "activeExperts": null, "arch": "Dense (MHA+ALiBi) · heavy KV", "dev": "Inception / G42 (UAE)", "url": "https://huggingface.co/inceptionai/jais-family-30b-16k"},
{"name": "ALLaM-7B (Arabic)", "params": 7, "active": 7, "hidden": 4096, "layers": 32, "kvHeads": 32, "headDim": 128, "ctx": 4096, "experts": null, "activeExperts": null, "arch": "Dense (MHA, Llama-2 base)", "dev": "SDAIA (KSA)", "url": "https://huggingface.co/ALLaM-AI/ALLaM-7B-Instruct-preview"},
{"name": "Fanar-1-9B (Arabic, Qatar)", "params": 9.2, "active": 9.2, "hidden": 3584, "layers": 42, "kvHeads": 8, "headDim": 256, "ctx": 8192, "experts": null, "activeExperts": null, "arch": "Dense (GQA+SWA, Gemma2 base)", "dev": "QCRI (Qatar)", "url": "https://huggingface.co/QCRI/Fanar-1-9B-Instruct"},
{"name": "K2-Think 32B (reasoning)", "params": 32.8, "active": 32.8, "hidden": 5120, "layers": 64, "kvHeads": 8, "headDim": 128, "ctx": 32768, "experts": null, "activeExperts": null, "arch": "Dense (GQA, Qwen2.5 base)", "dev": "MBZUAI / G42 (UAE)", "url": "https://huggingface.co/LLM360/K2-Think"},
{"name": "Llama 3.2 3B", "params": 3.2, "active": 3.2, "hidden": 3072, "layers": 28, "kvHeads": 8, "headDim": 128, "ctx": 131072, "experts": null, "activeExperts": null, "arch": "Dense (GQA)", "dev": "Meta", "url": "https://huggingface.co/meta-llama/Llama-3.2-3B-Instruct"},
{"name": "Kimi K3 2.8T-A50B (MoE)", "params": 2800, "active": 50, "hidden": 9216, "layers": 80, "kvHeads": 1, "headDim": 72, "ctx": 1000000, "experts": 896, "activeExperts": 16, "arch": "MoE (896E/16A, KDA hybrid + MLA eff., est. cfg)", "dev": "Moonshot AI", "url": "https://huggingface.co/blog/ResterChed/kimi-k3-model-overview-mxfp4-quantization-open-wei"},
{"name": "Jais-2-70B (Arabic)", "params": 70, "active": 70, "hidden": 8192, "layers": 80, "kvHeads": 8, "headDim": 128, "ctx": 32768, "experts": null, "activeExperts": null, "arch": "Dense (GQA, est. cfg) · from scratch, Cerebras-trained", "dev": "Inception / G42 (UAE)", "url": "https://huggingface.co/inceptionai"},
{"name": "Jais-2-8B (Arabic)", "params": 8, "active": 8, "hidden": 4096, "layers": 32, "kvHeads": 8, "headDim": 128, "ctx": 32768, "experts": null, "activeExperts": null, "arch": "Dense (GQA, est. cfg) · from scratch, Cerebras-trained", "dev": "Inception / G42 (UAE)", "url": "https://huggingface.co/inceptionai"},
{"name": "Jais-adapted-70B (Arabic)", "params": 70, "active": 70, "hidden": 8192, "layers": 80, "kvHeads": 8, "headDim": 128, "ctx": 4096, "experts": null, "activeExperts": null, "arch": "Dense (GQA, Llama-2 adapted)", "dev": "Inception / G42 (UAE)", "url": "https://huggingface.co/inceptionai/jais-adapted-70b"},
{"name": "Fanar-2-27B (Arabic, Qatar)", "params": 27.4, "active": 27.4, "hidden": 5376, "layers": 62, "kvHeads": 16, "headDim": 128, "ctx": 131072, "experts": null, "activeExperts": null, "arch": "Dense (GQA + SWA 5:1, win 1024) · Gemma-3-27B continual pretrain", "dev": "QCRI (Qatar)", "url": "https://huggingface.co/QCRI/Fanar-2-27B-Instruct", "kvGlobal": 10, "kvWin": 1024},
{"name": "ALLaM-34B (Arabic)", "params": 34, "active": 34, "hidden": 7168, "layers": 60, "kvHeads": 8, "headDim": 128, "ctx": 32768, "experts": null, "activeExperts": null, "arch": "Dense (GQA, est. cfg) · from scratch", "dev": "HUMAIN (KSA)", "url": "https://www.middleeastainews.com/p/humain-chat-live-allam-34b-llm"},
{"name": "Falcon-H1-Arabic-34B", "params": 34, "active": 34, "hidden": 5120, "layers": 72, "kvHeads": 4, "headDim": 128, "ctx": 262144, "experts": null, "activeExperts": null, "arch": "Dense hybrid Attn+SSM (GQA-4) · OALL #1", "dev": "TII (UAE)", "url": "https://huggingface.co/blog/tiiuae/falcon-h1-arabic"},
{"name": "Falcon-Arabic-7B", "params": 7, "active": 7, "hidden": 3072, "layers": 28, "kvHeads": 4, "headDim": 256, "ctx": 32768, "experts": null, "activeExperts": null, "arch": "Dense (GQA) · Falcon3-7B base", "dev": "TII (UAE)", "url": "https://www.tii.ae/news/middle-easts-leading-ai-powerhouse-tii-launches-two-new-ai-models-falcon-arabic-first-arabic"},
{"name": "SILMA-9B (Arabic)", "params": 9, "active": 9, "hidden": 3584, "layers": 42, "kvHeads": 8, "headDim": 256, "ctx": 8192, "experts": null, "activeExperts": null, "arch": "Dense (GQA + SWA 1:1, win 4096) · Gemma-2-9B base", "dev": "SILMA AI (KSA)", "url": "https://huggingface.co/silma-ai/SILMA-9B-Instruct-v1.0", "kvGlobal": 21, "kvWin": 4096},
{"name": "Cohere Command A+ 218B-A25B (MoE)", "params": 218, "active": 25, "hidden": 6144, "layers": 48, "kvHeads": 8, "headDim": 128, "ctx": 131072, "experts": null, "activeExperts": null, "arch": "MoE (25B active, est. cfg) · Apache 2.0, vision-in", "dev": "Cohere", "url": "https://docs.cohere.com/docs/command-a-plus"},
{"name": "Cohere Command A Reasoning 111B", "params": 111, "active": 111, "hidden": 12288, "layers": 64, "kvHeads": 8, "headDim": 128, "ctx": 262144, "experts": null, "activeExperts": null, "arch": "Dense (hybrid SWA, est. cfg) · reasoning", "dev": "Cohere", "url": "https://docs.cohere.com/docs/models"},
{"name": "Cohere Command R+ 104B", "params": 104, "active": 104, "hidden": 12288, "layers": 64, "kvHeads": 8, "headDim": 128, "ctx": 131072, "experts": null, "activeExperts": null, "arch": "Dense (GQA)", "dev": "Cohere", "url": "https://huggingface.co/CohereLabs/c4ai-command-r-plus-08-2024"},
{"name": "Cohere Command R 32B (08-2024)", "params": 32.3, "active": 32.3, "hidden": 8192, "layers": 40, "kvHeads": 8, "headDim": 128, "ctx": 131072, "experts": null, "activeExperts": null, "arch": "Dense (GQA)", "dev": "Cohere", "url": "https://huggingface.co/CohereLabs/c4ai-command-r-08-2024"},
{"name": "Cohere Command R7B", "params": 8, "active": 8, "hidden": 4096, "layers": 32, "kvHeads": 8, "headDim": 128, "ctx": 131072, "experts": null, "activeExperts": null, "arch": "Dense (GQA, 3:1 SWA)", "dev": "Cohere", "url": "https://huggingface.co/CohereLabs/c4ai-command-r7b-12-2024"},
{"name": "Cohere Command R7B Arabic", "params": 8, "active": 8, "hidden": 4096, "layers": 32, "kvHeads": 8, "headDim": 128, "ctx": 131072, "experts": null, "activeExperts": null, "arch": "Dense (GQA, 3:1 SWA) · Arabic-optimized", "dev": "Cohere", "url": "https://huggingface.co/CohereLabs/c4ai-command-r7b-arabic-02-2025"},
{"name": "Aya Expanse 32B (multilingual)", "params": 32.3, "active": 32.3, "hidden": 8192, "layers": 40, "kvHeads": 8, "headDim": 128, "ctx": 131072, "experts": null, "activeExperts": null, "arch": "Dense (GQA) · 23 languages incl. Arabic", "dev": "Cohere", "url": "https://huggingface.co/CohereLabs/aya-expanse-32b"},
{"name": "Aya Expanse 8B (multilingual)", "params": 8, "active": 8, "hidden": 4096, "layers": 32, "kvHeads": 8, "headDim": 128, "ctx": 8192, "experts": null, "activeExperts": null, "arch": "Dense (GQA) · 23 languages incl. Arabic", "dev": "Cohere", "url": "https://huggingface.co/CohereLabs/aya-expanse-8b"},
{"name": "Mistral Saba 24B (MENA/S-Asia)", "params": 24, "active": 24, "hidden": 5120, "layers": 40, "kvHeads": 8, "headDim": 128, "ctx": 32768, "experts": null, "activeExperts": null, "arch": "Dense (GQA, est. cfg) · Arabic-focused, on-prem", "dev": "Mistral AI", "url": "https://mistral.ai/news/mistral-saba/"},
{"name": "AceGPT-v2-32B (Arabic)", "params": 32.5, "active": 32.5, "hidden": 5120, "layers": 64, "kvHeads": 8, "headDim": 128, "ctx": 32768, "experts": null, "activeExperts": null, "arch": "Dense (GQA, Qwen1.5-32B base) · native-alignment pretrain", "dev": "FreedomIntelligence + KAUST (KSA)", "url": "https://huggingface.co/FreedomIntelligence/AceGPT-v2-32B-Chat"},
{"name": "AceGPT-v2-70B (Arabic)", "params": 70.6, "active": 70.6, "hidden": 8192, "layers": 80, "kvHeads": 8, "headDim": 128, "ctx": 8192, "experts": null, "activeExperts": null, "arch": "Dense (GQA, Llama-3-70B base)", "dev": "FreedomIntelligence + KAUST (KSA)", "url": "https://huggingface.co/FreedomIntelligence/AceGPT-v2-70B-Chat"},
{"name": "Falcon-H1R-7B (reasoning)", "params": 7.6, "active": 7.6, "hidden": 3072, "layers": 44, "kvHeads": 2, "headDim": 128, "ctx": 262144, "experts": null, "activeExperts": null, "arch": "Dense hybrid Attn+SSM (GQA-2) · reasoning, GRPO", "dev": "TII (UAE)", "url": "https://huggingface.co/tiiuae/Falcon-H1R-7B"},
{"name": "Fanar-2-Oryx-IVU 7B (Arabic VLM)", "params": 8.3, "active": 8.3, "hidden": 3584, "layers": 28, "kvHeads": 4, "headDim": 128, "ctx": 128000, "experts": null, "activeExperts": null, "arch": "Dense (GQA) VLM · Qwen2.5-VL-7B base, image+video", "dev": "QCRI (Qatar)", "url": "https://huggingface.co/QCRI/Fanar-2-Oryx-IVU"},
{"name": "AIN-7B (Arabic VLM)", "params": 8.3, "active": 8.3, "hidden": 3584, "layers": 28, "kvHeads": 4, "headDim": 128, "ctx": 32768, "experts": null, "activeExperts": null, "arch": "Dense (GQA) VLM · Qwen2-VL-7B base, MIT license", "dev": "MBZUAI (UAE)", "url": "https://huggingface.co/MBZUAI/AIN"},
{"name": "SILMA-Kashif-2B (Arabic RAG)", "params": 2.6, "active": 2.6, "hidden": 2304, "layers": 26, "kvHeads": 4, "headDim": 256, "ctx": 12288, "experts": null, "activeExperts": null, "arch": "Dense (GQA+SWA) · Gemma-2-2B base, RAG-tuned", "dev": "SILMA AI (KSA)", "url": "https://huggingface.co/silma-ai/SILMA-Kashif-2B-Instruct-v1.0"},
{"name": "Nile-Chat-3x4B MoE (Egyptian Arabic)", "params": 12, "active": 6, "hidden": 2560, "layers": 34, "kvHeads": 4, "headDim": 43, "ctx": 131072, "experts": 3, "activeExperts": 2, "arch": "MoE (3x Gemma-3-4B experts) · hybrid SWA eff. KV", "dev": "MBZUAI-Paris (UAE)", "url": "https://huggingface.co/MBZUAI-Paris/Nile-Chat-3x4B-A6B"},
{"name": "Magistral Small 1.2 24B (reasoning)", "params": 24, "active": 24, "hidden": 5120, "layers": 40, "kvHeads": 8, "headDim": 128, "ctx": 131072, "experts": null, "activeExperts": null, "arch": "Dense (GQA) · reasoning", "dev": "Mistral AI", "url": "https://huggingface.co/mistralai/Magistral-Small-2509"},
{"name": "Mistral Large 2 123B", "params": 123, "active": 123, "hidden": 12288, "layers": 88, "kvHeads": 8, "headDim": 128, "ctx": 131072, "experts": null, "activeExperts": null, "arch": "Dense (GQA)", "dev": "Mistral AI", "url": "https://huggingface.co/mistralai/Mistral-Large-Instruct-2407"},
{"name": "Ministral 8B", "params": 8, "active": 8, "hidden": 4096, "layers": 36, "kvHeads": 8, "headDim": 128, "ctx": 131072, "experts": null, "activeExperts": null, "arch": "Dense (GQA, interleaved SWA)", "dev": "Mistral AI", "url": "https://huggingface.co/mistralai/Ministral-8B-Instruct-2410"},
{"name": "Mistral Small 4 24B", "params": 24, "active": 24, "hidden": 5120, "layers": 40, "kvHeads": 8, "headDim": 128, "ctx": 131072, "experts": null, "activeExperts": null, "arch": "Dense (GQA, est. cfg) · Apache 2.0", "dev": "Mistral AI", "url": "https://mistral.ai/news/"}
];
const GPUS = [
{"name": "RTX 4060 Ti 16GB", "vram": 16, "bw": 0.288, "tflops": 44, "mem": "GDDR6", "arch": "Ada Lovelace", "watts": 165, "cls": "Consumer", "link": "PCIe 4.0", "url": "https://www.nvidia.com/en-us/geforce/graphics-cards/40-series/", "part": {"kind": "frac"}},
{"name": "RTX 4070 Ti Super 16GB", "vram": 16, "bw": 0.672, "tflops": 88, "mem": "GDDR6X", "arch": "Ada Lovelace", "watts": 285, "cls": "Consumer", "link": "PCIe 4.0", "url": "https://www.nvidia.com/en-us/geforce/graphics-cards/40-series/", "part": {"kind": "frac"}},
{"name": "RTX 4080 Super 16GB", "vram": 16, "bw": 0.736, "tflops": 104, "mem": "GDDR6X", "arch": "Ada Lovelace", "watts": 320, "cls": "Consumer", "link": "PCIe 4.0", "url": "https://www.nvidia.com/en-us/geforce/graphics-cards/40-series/", "part": {"kind": "frac"}},
{"name": "RTX 4090 24GB", "vram": 24, "bw": 1.008, "tflops": 165, "mem": "GDDR6X", "arch": "Ada Lovelace", "watts": 450, "cls": "Consumer", "link": "PCIe 4.0", "url": "https://www.nvidia.com/en-us/geforce/graphics-cards/40-series/", "part": {"kind": "frac"}},
{"name": "RTX 5070 Ti 16GB", "vram": 16, "bw": 0.896, "tflops": 88, "mem": "GDDR7", "arch": "Blackwell", "watts": 300, "cls": "Consumer", "link": "PCIe 5.0", "url": "https://www.nvidia.com/en-us/geforce/graphics-cards/50-series/", "part": {"kind": "frac"}},
{"name": "RTX 5080 16GB", "vram": 16, "bw": 0.96, "tflops": 113, "mem": "GDDR7", "arch": "Blackwell", "watts": 360, "cls": "Consumer", "link": "PCIe 5.0", "url": "https://www.nvidia.com/en-us/geforce/graphics-cards/50-series/", "part": {"kind": "frac"}},
{"name": "RTX 5090 32GB", "vram": 32, "bw": 1.792, "tflops": 210, "mem": "GDDR7", "arch": "Blackwell", "watts": 575, "cls": "Consumer", "link": "PCIe 5.0", "url": "https://www.nvidia.com/en-us/geforce/graphics-cards/50-series/", "part": {"kind": "frac"}},
{"name": "RTX 6000 Ada 48GB", "vram": 48, "bw": 0.96, "tflops": 182, "mem": "GDDR6", "arch": "Ada Lovelace", "watts": 300, "cls": "Workstation", "link": "PCIe 4.0", "url": "https://www.nvidia.com/en-us/products/workstations/rtx-6000/", "part": {"kind": "frac"}},
{"name": "RTX PRO 6000 Blackwell Server Edition 96GB", "vram": 96, "bw": 1.597, "tflops": 250, "mem": "GDDR7", "arch": "Blackwell", "watts": 600, "cls": "Server / Workstation", "link": "PCIe 5.0", "url": "https://www.nvidia.com/en-us/data-center/rtx-pro-6000-blackwell-server-edition/", "part": {"kind": "mig", "max": 4, "min": 24}},
{"name": "A100 40GB SXM", "vram": 40, "bw": 1.555, "tflops": 312, "mem": "HBM2e", "arch": "Ampere", "watts": 400, "cls": "Data Center", "link": "NVLink Gen3", "url": "https://www.nvidia.com/en-us/data-center/a100/", "part": {"kind": "mig", "max": 7, "min": 5}},
{"name": "A100 80GB SXM", "vram": 80, "bw": 2.039, "tflops": 312, "mem": "HBM2e", "arch": "Ampere", "watts": 400, "cls": "Data Center", "link": "NVLink Gen3", "url": "https://www.nvidia.com/en-us/data-center/a100/", "part": {"kind": "mig", "max": 7, "min": 10}},
{"name": "A100 80GB PCIe", "vram": 80, "bw": 1.935, "tflops": 312, "mem": "HBM2e", "arch": "Ampere", "watts": 300, "cls": "Data Center", "link": "PCIe 4.0", "url": "https://www.nvidia.com/en-us/data-center/a100/", "part": {"kind": "mig", "max": 7, "min": 10}},
{"name": "L4 24GB", "vram": 24, "bw": 0.3, "tflops": 60.5, "mem": "GDDR6", "arch": "Ada Lovelace", "watts": 72, "cls": "Data Center", "link": "PCIe 4.0", "url": "https://www.nvidia.com/en-us/data-center/l4/", "part": {"kind": "frac"}},
{"name": "L40 48GB", "vram": 48, "bw": 0.864, "tflops": 90.5, "mem": "GDDR6", "arch": "Ada Lovelace", "watts": 300, "cls": "Data Center", "link": "PCIe 4.0", "url": "https://www.nvidia.com/en-us/data-center/l40/", "part": {"kind": "frac"}},
{"name": "L40S 48GB", "vram": 48, "bw": 0.864, "tflops": 183, "mem": "GDDR6", "arch": "Ada Lovelace", "watts": 350, "cls": "Data Center", "link": "PCIe 4.0", "url": "https://www.nvidia.com/en-us/data-center/l40s/", "part": {"kind": "frac"}},
{"name": "H100 NVL 94GB", "vram": 94, "bw": 3.9, "tflops": 835, "mem": "HBM3", "arch": "Hopper", "watts": 350, "cls": "Data Center", "link": "NVLink Gen4", "url": "https://www.nvidia.com/en-us/data-center/h100/", "part": {"kind": "mig", "max": 7, "min": 12}},
{"name": "H100 80GB SXM", "vram": 80, "bw": 3.35, "tflops": 989, "mem": "HBM3", "arch": "Hopper", "watts": 700, "cls": "Data Center", "link": "NVLink Gen4", "url": "https://www.nvidia.com/en-us/data-center/h100/", "part": {"kind": "mig", "max": 7, "min": 10}},
{"name": "H100 80GB PCIe", "vram": 80, "bw": 2, "tflops": 756, "mem": "HBM2e", "arch": "Hopper", "watts": 350, "cls": "Data Center", "link": "PCIe 5.0", "url": "https://www.nvidia.com/en-us/data-center/h100/", "part": {"kind": "mig", "max": 7, "min": 10}},
{"name": "H200 141GB NVL", "vram": 141, "bw": 4.8, "tflops": 989, "mem": "HBM3e", "arch": "Hopper", "watts": 600, "cls": "Data Center", "link": "NVLink Gen4", "url": "https://www.nvidia.com/en-us/data-center/h200/", "part": {"kind": "mig", "max": 7, "min": 18}},
{"name": "H200 141GB SXM", "vram": 141, "bw": 4.8, "tflops": 989, "mem": "HBM3e", "arch": "Hopper", "watts": 700, "cls": "Data Center", "link": "NVLink Gen4", "url": "https://www.nvidia.com/en-us/data-center/h200/", "part": {"kind": "mig", "max": 7, "min": 18}},
{"name": "B200 180GB", "vram": 180, "bw": 8, "tflops": 2250, "mem": "HBM3e", "arch": "Blackwell", "watts": 1000, "cls": "Data Center", "link": "NVLink Gen5", "url": "https://www.nvidia.com/en-us/data-center/dgx-b200/", "part": {"kind": "mig", "max": 7, "min": 23}},
{"name": "B300 288GB", "vram": 288, "bw": 8, "tflops": 2250, "mem": "HBM3e", "arch": "Blackwell Ultra", "watts": 1200, "cls": "Data Center", "link": "NVLink Gen5", "url": "https://www.nvidia.com/en-us/data-center/dgx-b300/", "part": {"kind": "mig", "max": 7, "min": 34}},
{"name": "Apple M2 Ultra 192GB", "vram": 192, "bw": 0.8, "tflops": 27.2, "mem": "Unified LPDDR5", "arch": "Apple M2", "watts": 215, "cls": "Apple Silicon", "link": "—", "url": "https://www.apple.com/newsroom/2023/06/apple-introduces-m2-ultra/", "part": {"kind": "frac"}},
{"name": "Apple M4 Max 128GB", "vram": 128, "bw": 0.546, "tflops": 38, "mem": "Unified LPDDR5X", "arch": "Apple M4", "watts": 150, "cls": "Apple Silicon", "link": "—", "url": "https://www.apple.com/macbook-pro/", "part": {"kind": "frac"}},
{"name": "AMD Instinct MI300X 192GB", "vram": 192, "bw": 5.3, "tflops": 1307, "mem": "HBM3", "arch": "CDNA 3", "watts": 750, "cls": "Data Center", "link": "Infinity Fabric", "url": "https://www.amd.com/en/products/accelerators/instinct/mi300/mi300x.html", "part": {"kind": "cpx", "max": 8, "min": 24}},
{"name": "AMD Instinct MI325X 256GB", "vram": 256, "bw": 6, "tflops": 1307, "mem": "HBM3E", "arch": "CDNA 3", "watts": 1000, "cls": "Data Center", "link": "Infinity Fabric", "url": "https://www.amd.com/en/products/accelerators/instinct/mi325x.html", "part": {"kind": "cpx", "max": 8, "min": 32}},
{"name": "AMD Instinct MI355X 288GB", "vram": 288, "bw": 8, "tflops": 2513, "mem": "HBM3E", "arch": "CDNA 4", "watts": 1400, "cls": "Data Center", "link": "Infinity Fabric", "url": "https://www.amd.com/en/products/accelerators/instinct/mi350.html", "part": {"kind": "cpx", "max": 8, "min": 36}},
{"name": "NVIDIA GB200 186GB (per GPU)", "vram": 186, "bw": 8, "tflops": 2250, "mem": "HBM3e", "arch": "Blackwell (Grace)", "watts": 1200, "cls": "Data Center", "link": "NVLink Gen5", "url": "https://www.nvidia.com/en-us/data-center/gb200-nvl72/", "part": {"kind": "mig", "max": 7, "min": 23}},
{"name": "Apple M3 Ultra 256GB", "vram": 256, "bw": 0.819, "tflops": 28, "mem": "Unified LPDDR5", "arch": "Apple M3", "watts": 270, "cls": "Apple Silicon", "link": "—", "url": "https://www.apple.com/mac-studio/", "part": {"kind": "frac"}},
{"name": "Intel Gaudi 3 128GB", "vram": 128, "bw": 3.7, "tflops": 1835, "mem": "HBM2e", "arch": "Intel Gaudi 3", "watts": 900, "cls": "Data Center", "link": "RoCE / Ethernet", "url": "https://www.intel.com/content/www/us/en/products/details/processors/ai-accelerators/gaudi3.html", "part": {"kind": "whole"}},
{"name": "GH200 141GB", "vram": 141, "bw": 4.9, "tflops": 989, "mem": "HBM3e", "arch": "Grace Hopper", "watts": 1000, "cls": "Data Center", "link": "NVLink-C2C", "url": "https://www.nvidia.com/en-us/data-center/grace-hopper-superchip/", "part": {"kind": "mig", "max": 7, "min": 18}},
{"name": "GB300 288GB (per GPU)", "vram": 288, "bw": 8, "tflops": 2250, "mem": "HBM3e", "arch": "Blackwell Ultra", "watts": 1400, "cls": "Data Center", "link": "NVLink Gen5", "url": "https://www.nvidia.com/en-us/data-center/gb300-nvl72/", "part": {"kind": "mig", "max": 7, "min": 35}},
{"name": "AMD Instinct MI350X 288GB", "vram": 288, "bw": 8, "tflops": 2300, "mem": "HBM3E", "arch": "CDNA 4", "watts": 1000, "cls": "Data Center", "link": "Infinity Fabric", "url": "https://www.amd.com/en/products/accelerators/instinct/mi350.html", "part": {"kind": "cpx", "max": 8, "min": 36}},
{"name": "AMD Instinct MI455X 432GB", "vram": 432, "bw": 19.6, "tflops": 5000, "mem": "HBM4", "arch": "CDNA 5", "watts": 2000, "cls": "Data Center (H2 2026)", "link": "IF + UALink", "url": "https://www.amd.com/en/products/accelerators/instinct.html", "part": {"kind": "cpx", "max": 8, "min": 54}},
{"name": "NVIDIA Rubin VR200 288GB", "vram": 288, "bw": 20.5, "tflops": 8300, "mem": "HBM4", "arch": "Rubin", "watts": 1800, "cls": "Data Center (H2 2026)", "link": "NVLink Gen6", "url": "https://www.nvidia.com/en-us/data-center/vera-rubin/", "part": {"kind": "mig", "max": 7, "min": 36}},
{"name": "NVIDIA DGX Spark 128GB (GB10)", "vram": 128, "bw": 0.273, "tflops": 125, "mem": "Unified LPDDR5x", "arch": "Grace Blackwell", "watts": 240, "cls": "Desktop", "link": "NVLink-C2C", "url": "https://www.nvidia.com/en-us/products/workstations/dgx-spark/", "part": {"kind": "frac"}},
{"name": "Apple M3 Ultra 512GB", "vram": 512, "bw": 0.819, "tflops": 28, "mem": "Unified LPDDR5", "arch": "Apple M3", "watts": 270, "cls": "Apple Silicon", "link": "—", "url": "https://www.apple.com/mac-studio/", "part": {"kind": "frac"}}
];
const QUANTS = [
{"name": "FP32", "bits": 32, "bytes": 4, "quality": "100% (baseline)", "speed": "Slowest", "use": "Training / research only", "hw": "All GPUs"},
{"name": "FP16", "bits": 16, "bytes": 2, "quality": "~99-100%", "speed": "Fast", "use": "Default inference & training", "hw": "All modern GPUs"},
{"name": "BF16", "bits": 16, "bytes": 2, "quality": "~99-100%", "speed": "Fast", "use": "Default inference on BF16-native hardware", "hw": "Ampere+ / BF16-capable GPUs"},
{"name": "FP8", "bits": 8, "bytes": 1, "quality": "~97-99%", "speed": "Very Fast", "use": "Production inference", "hw": "Hopper+ (H100/H200/B200, RTX 50)"},
{"name": "NV FP4", "bits": 4.5, "bytes": 0.5625, "quality": "~94-97%", "speed": "Fastest", "use": "Blackwell native inference (incl. block scales)", "hw": "Blackwell only (B200, RTX 50)"},
{"name": "INT8", "bits": 8, "bytes": 1, "quality": "~95-98%", "speed": "Fast", "use": "Optimized inference (bitsandbytes)", "hw": "All (Tensor Cores)"},
{"name": "INT4", "bits": 4, "bytes": 0.5, "quality": "~92-96%", "speed": "Fastest", "use": "GPTQ/AWQ deployment (+~6% group scales not counted)", "hw": "All GPUs (software)"},
{"name": "Q8_0", "bits": 8, "bytes": 1, "quality": "~99%", "speed": "Fast", "use": "GGUF near-lossless", "hw": "All (llama.cpp)"},
{"name": "Q6_K", "bits": 6.5, "bytes": 0.8125, "quality": "~97-99%", "speed": "Fast", "use": "GGUF high quality", "hw": "All (llama.cpp)"},
{"name": "Q5_K_M", "bits": 5.5, "bytes": 0.6875, "quality": "~96-98%", "speed": "Faster", "use": "GGUF recommended balance", "hw": "All (llama.cpp)"},
{"name": "Q5_K_S", "bits": 5.5, "bytes": 0.69, "quality": "~95-97%", "speed": "Faster", "use": "GGUF good quality, smaller", "hw": "All (llama.cpp)"},
{"name": "Q4_K_M", "bits": 4.5, "bytes": 0.575, "quality": "~93-96%", "speed": "Fastest", "use": "GGUF most popular (Ollama default)", "hw": "All (llama.cpp)"},
{"name": "Q4_K_S", "bits": 4.3, "bytes": 0.5375, "quality": "~92-95%", "speed": "Fastest", "use": "GGUF smaller Q4 variant", "hw": "All (llama.cpp)"},
{"name": "Q4_0", "bits": 4, "bytes": 0.5, "quality": "~91-94%", "speed": "Fastest", "use": "GGUF basic 4-bit", "hw": "All (llama.cpp)"},
{"name": "Q3_K_M", "bits": 3.5, "bytes": 0.4375, "quality": "~88-93%", "speed": "Fastest", "use": "GGUF aggressive compression", "hw": "All (llama.cpp)"},
{"name": "Q3_K_L", "bits": 3.9, "bytes": 0.4875, "quality": "~90-94%", "speed": "Fastest", "use": "GGUF large Q3 variant", "hw": "All (llama.cpp)"},
{"name": "Q3_K_S", "bits": 3.4, "bytes": 0.425, "quality": "~85-90%", "speed": "Fastest", "use": "GGUF small Q3", "hw": "All (llama.cpp)"},
{"name": "Q2_K", "bits": 2.6, "bytes": 0.32, "quality": "~80-88%", "speed": "Fastest", "use": "GGUF extreme (quality loss)", "hw": "All (llama.cpp)"},
{"name": "MXFP4", "bits": 4.25, "bytes": 0.53125, "quality": "~93-96%", "speed": "Fastest", "use": "GPT-OSS native / OCP microscaling (incl. scales)", "hw": "Blackwell native; Hopper via SW"}
];
const CASES = [
{"name": "Simple chatbot", "resident": 4096, "reasoning": "None", "visibleOut": 250, "ttftTarget": 300, "tpsTarget": 20, "p95Target": 18, "model": "Llama 3.1 8B", "note": "Short support chat. 20 tok/s outruns reading speed; a 250-tok reply streams in ~13 s.", "supports": ["guard"], "traffic": {"turns": 25, "calls": 1.3, "durS": 4, "burst": 2, "pct": "~8%"}},
{"name": "Simple RAG", "resident": 8192, "reasoning": "None", "visibleOut": 300, "ttftTarget": 400, "tpsTarget": 25, "p95Target": 18, "model": "Qwen3 8B", "note": "Single-pass RAG. TTFT budget includes retrieval + rerank (~400 ms) ahead of prefill.", "supports": ["embed", "rerank"], "traffic": {"turns": 18, "calls": 2, "durS": 5, "burst": 2, "pct": "~10%"}},
{"name": "Advanced RAG", "resident": 32768, "reasoning": "Custom", "reasonTok": 800, "visibleOut": 400, "ttftTarget": 1200, "tpsTarget": 40, "p95Target": 45, "model": "Qwen3 32B", "note": "Multi-hop agentic RAG: 16-32K context, ~800 thinking/tool-plan tokens per call on reasoning models, ~6 LLM calls per answer.", "supports": ["embed", "rerank"], "traffic": {"turns": 10, "calls": 6, "durS": 8, "burst": 2, "pct": "~27%"}},
{"name": "Internal GPT / Copilot", "resident": 16384, "reasoning": "None", "visibleOut": 300, "ttftTarget": 600, "tpsTarget": 25, "p95Target": 18, "model": "Llama 3.3 70B Instruct", "note": "Enterprise assistant with doc retrieval, multi-turn; prefix caching assumed for history.", "supports": ["embed", "rerank"], "traffic": {"turns": 3, "calls": 1.5, "durS": 9, "burst": 2.5, "pct": "~3%"}},
{"name": "Document Q&A", "resident": 32768, "reasoning": "Custom", "reasonTok": 500, "visibleOut": 300, "ttftTarget": 2500, "tpsTarget": 30, "p95Target": 40, "model": "Qwen3 32B", "note": "Long doc in context with a light grounded-verification budget (~500 thinking tokens); TTFT is dominated by the 32K prefill.", "supports": ["ocr", "embed", "rerank"], "traffic": {"turns": 10, "calls": 2, "durS": 12, "burst": 1.5, "pct": "~10%"}},
{"name": "Document generation", "resident": 8192, "reasoning": "None", "visibleOut": 2000, "ttftTarget": 1000, "tpsTarget": 40, "p95Target": 70, "model": "Llama 3.3 70B Instruct", "note": "Long-form drafting. Users skim, not read along: 40 tok/s, a 2K draft streams in ~50 s.", "supports": [], "traffic": {"turns": 7, "calls": 1.5, "durS": 28, "burst": 1.5, "pct": "~12%"}},
{"name": "Code generation", "resident": 8192, "reasoning": "None", "visibleOut": 60, "ttftTarget": 100, "tpsTarget": 60, "p95Target": 2, "model": "Qwen3 4B", "note": "IDE completion / small edits: 10-100 token suggestions; anything slower than ~2 s gets discarded, so P95 is tight.", "supports": ["embed"], "traffic": {"turns": 65, "calls": 1, "durS": 1.3, "burst": 3, "pct": "~7%"}},
{"name": "Code agent (Cline/Cursor-style)", "resident": 65536, "reasoning": "Custom", "reasonTok": 1500, "visibleOut": 500, "ttftTarget": 1000, "tpsTarget": 50, "p95Target": 60, "model": "Qwen3-Next 80B-A3B (MoE, hybrid)", "note": "Repo-aware coding agent: 32-64K append-only context, ~2K tokens per tool step (thinking + diff), ~30 steps per 20-30 min task.", "supports": ["embed"], "traffic": {"turns": 2, "calls": 30, "durS": 40, "burst": 1.5, "pct": "~100%: an engaged user keeps one agent stream busy"}},
{"name": "Voice agent (real-time)", "resident": 4096, "reasoning": "None", "visibleOut": 100, "ttftTarget": 200, "tpsTarget": 50, "p95Target": 3.5, "session": {"min": 5, "tokMin": 200, "base": 3100}, "model": "Qwen3 8B", "note": "Telephony/IVR. Voice-to-voice budget needs LLM TTFT under ~300 ms; 50 tok/s feeds sentence-chunked TTS without gaps.", "supports": ["asr", "tts"], "policy": "all", "traffic": {"direct": 1, "pct": "100%: callers are the concurrency"}},
{"name": "Reasoning agent (light)", "resident": 8192, "reasoning": "Light reasoning", "visibleOut": 300, "ttftTarget": 600, "tpsTarget": 60, "p95Target": 55, "model": "Magistral Small 1.2 24B (reasoning)", "note": "~2K hidden CoT + short answer. Nobody reads CoT: decode speed is the latency lever, so target 60 tok/s.", "supports": [], "traffic": {"turns": 8, "calls": 3.5, "durS": 39, "burst": 1.5, "pct": "~45%"}},
{"name": "Reasoning agent (heavy)", "resident": 16384, "reasoning": "Heavy reasoning", "visibleOut": 500, "ttftTarget": 800, "tpsTarget": 60, "p95Target": 200, "model": "DeepSeek-R1 671B (MoE)", "note": "~8K CoT budget (math/coding/research). 8.5K tokens at 60 tok/s is a ~142 s physical floor.", "supports": [], "traffic": {"turns": 3, "calls": 5, "durS": 142, "burst": 1.5, "pct": "~89%"}},
{"name": "Video summarization", "resident": 32768, "reasoning": "Custom", "reasonTok": 2000, "visibleOut": 500, "ttftTarget": 3000, "tpsTarget": 40, "p95Target": 90, "model": "Gemma 3 27B", "note": "Chunked VLM captioning then aggregate; ~30-47K vision tokens per minute of video at native sampling.", "supports": ["asr"], "traffic": {"turns": 2, "calls": 12, "durS": 10, "burst": 1.5, "pct": "~10%"}},
{"name": "Long-doc analysis (legal/financial)", "resident": 65536, "reasoning": "Custom", "reasonTok": 1000, "visibleOut": 800, "ttftTarget": 5000, "tpsTarget": 30, "p95Target": 90, "model": "Qwen3 32B", "note": "64-128K contracts/filings. TTFT is the long prefill (~5 s at 64K tuned); prefix caching helps repeat queries.", "supports": ["ocr"], "traffic": {"turns": 2.5, "calls": 20, "durS": 10, "burst": 1.5, "pct": "~20%"}},
{"name": "Offline batch / extract", "resident": 4096, "reasoning": "None", "visibleOut": 500, "ttftTarget": 0, "tpsTarget": 0, "p95Target": 0, "model": "Qwen3 30B-A3B (MoE)", "note": "Batch jobs (extraction, classification): 24 h job SLA, no interactive SLOs; size for throughput at max batch.", "supports": ["ocr"], "traffic": {"direct": 1, "pct": "queue-set: enter jobs in flight, not people"}},
{"name": "Deep research agent (async)", "resident": 65536, "reasoning": "Custom", "reasonTok": 2000, "visibleOut": 500, "ttftTarget": 1000, "tpsTarget": 50, "p95Target": 75, "model": "Qwen3 235B-A22B (MoE)", "note": "Multi-step autonomous research: ~2K thinking tokens per call across ~40 calls (~35 min per task, ~100K output tokens total).", "supports": ["embed", "rerank"], "traffic": {"turns": 1, "calls": 40, "durS": 51, "burst": 1.5, "pct": "~85%"}},
{"name": "Medical imaging report assistant", "resident": 8192, "reasoning": "None", "visibleOut": 400, "ttftTarget": 1500, "tpsTarget": 50, "p95Target": 15, "model": "Gemma 3 27B", "note": "VLM reads a study (1-3K image tokens in context) and drafts findings/impression. Clinician-interactive.", "supports": ["ocr", "guard"], "traffic": {"turns": 12, "calls": 2, "durS": 8, "burst": 2, "pct": "~7%"}},
{"name": "Clinical knowledge assistant", "resident": 8192, "reasoning": "Custom", "reasonTok": 1000, "visibleOut": 350, "ttftTarget": 800, "tpsTarget": 40, "p95Target": 50, "model": "Llama 3.3 70B Instruct", "note": "Grounded medical Q&A with a real verification budget (~1K thinking tokens); guardrails on both directions.", "supports": ["embed", "rerank", "guard"], "traffic": {"turns": 4, "calls": 1.5, "durS": 8, "burst": 2.5, "pct": "~4%"}},
{"name": "Real-time video analytics", "resident": 8192, "reasoning": "None", "visibleOut": 80, "ttftTarget": 700, "tpsTarget": 40, "p95Target": 4, "model": "Gemma 3 4B", "note": "VLM monitors streams in ~10 s clips (~8K vision tokens each); alert within seconds. Concurrency = camera streams.", "supports": [], "traffic": {"direct": 1, "pct": "100%: camera streams are the concurrency"}},
{"name": "Translation / localization", "resident": 2048, "reasoning": "None", "visibleOut": 500, "ttftTarget": 500, "tpsTarget": 40, "p95Target": 18, "model": "Aya Expanse 32B (multilingual)", "note": "Segment/page translation, roughly symmetric input and output. Subtitle mode needs segments under ~2 s.", "supports": [], "traffic": {"turns": 30, "calls": 1.2, "durS": 11, "burst": 2, "pct": "~10%"}},
{"name": "Contact-center agent assist", "resident": 16384, "reasoning": "None", "visibleOut": 60, "ttftTarget": 400, "tpsTarget": 40, "p95Target": 3, "session": {"min": 8, "tokMin": 200, "base": 14784}, "model": "Qwen3 14B", "note": "Live suggestions while a human talks: transcript + KB in context, tiny outputs, utterance-to-suggestion under ~2.5 s.", "supports": ["asr", "embed", "rerank"], "policy": "all", "traffic": {"direct": 1, "pct": "100%: live assisted calls are the concurrency"}},
{"name": "Computer-use / browser agent", "resident": 65536, "reasoning": "Custom", "reasonTok": 1000, "visibleOut": 200, "ttftTarget": 2000, "tpsTarget": 30, "p95Target": 60, "model": "Llama 4 Scout 109B (MoE)", "note": "One STEP of an autonomous browser or desktop agent. A whole task runs about 200K tokens across many steps; each step re-sends the accumulated transcript plus 2-5K tokens of tool schema, and answers with a short tool call.", "supports": ["guard"], "traffic": {"turns": 4, "calls": 25, "durS": 8, "burst": 1.5, "pct": "~35%: each engaged user keeps an agent loop stepping"}},
{"name": "Speech-to-speech (native audio)", "resident": 4096, "reasoning": "None", "visibleOut": 150, "ttftTarget": 200, "tpsTarget": 50, "p95Target": 5, "policy": "all", "session": {"min": 5, "tokMin": 750, "base": 346}, "model": "Gemma 4 E4B", "note": "A model that takes audio in and emits audio out, with no separate ASR or TTS. Native stacks reach 160-400 ms voice-to-voice against 1-2 s for a pipeline, so the whole budget sits on this one model.", "supports": ["guard"], "traffic": {"direct": 1, "pct": "100%: live callers are the concurrency"}},
{"name": "Code review agent", "resident": 65536, "reasoning": "Custom", "reasonTok": 1500, "visibleOut": 800, "ttftTarget": 3000, "tpsTarget": 30, "p95Target": 110, "model": "Qwen3-Coder 480B-A35B (MoE)", "note": "A whole diff reviewed in one pass: about 50K tokens of prefill for a 2,000-line pull request, a long think, and a page of review comments. Prefill dominates.", "supports": ["embed"], "traffic": {"turns": 3, "calls": 1, "durS": 0, "burst": 2, "pct": "~10%"}},
{"name": "Code completion (panel)", "resident": 8192, "reasoning": "None", "visibleOut": 250, "ttftTarget": 300, "tpsTarget": 20, "p95Target": 18, "model": "Qwen3 4B", "note": "Sidebar or chat-panel completion, where the answer is read rather than accepted inline. The relaxed half of the completion class: 300 ms first token and reading-speed streaming.", "supports": ["embed"], "traffic": {"turns": 20, "calls": 1, "durS": 0, "burst": 3, "pct": "~4%"}}
];
const KV_QUANTS = [{name:'BF16',bytes:2},{name:'FP16',bytes:2},{name:'FP8',bytes:1},{name:'INT8',bytes:1},{name:'INT4',bytes:0.5}];
const REASON_TOK = {'None':0,'Light reasoning':2000,'Heavy reasoning':8000,'Custom':2000};
const RESIL = {
  n:   {code:0, label:'N',       long:'N · capacity only',                              mult:n=>0,              add:0, live:n=>n},
  n1:  {code:1, label:'N+1',     long:'N+1 · one standby worker',                       mult:n=>0,              add:1, live:n=>n},
  n2:  {code:7, label:'N+2',     long:'N+2 · two standby workers',                      mult:n=>0,              add:2, live:n=>n},
  nn:  {code:2, label:'N+N',     long:'N+N · in-site mirror (2N)',                      mult:n=>n,              add:0, live:n=>n},
  dr:  {code:3, label:'DR',      long:'DR · full standby site (active/passive)',        mult:n=>n,              add:0, live:n=>n},
  drh: {code:8, label:'DR ½',    long:'DR · half-size standby site (1.5N)',             mult:n=>Math.ceil(n/2), add:0, live:n=>n, degraded:true},
  aas: {code:9, label:'A/A ½+½', long:'Active/Active split · N across two sites (1x)',  mult:n=>0,              add:0, live:n=>n, degraded:true},
  aas1:{code:11,label:'A/A ½+½ +1',long:'Active/Active split · N across two sites + one spare (N+1)', mult:n=>0, add:1, live:n=>n, degraded:true},
  aass:{code:10,label:'A/A ½+½ +1/site',long:'Active/Active split · N across two sites + spare per site (N+2)', mult:n=>0, add:2, live:n=>n, degraded:true},
  aa:  {code:5, label:'A/A',     long:'Active/Active · two live sites (2N)',            mult:n=>n,              add:0, live:n=>2*n},
  aan1:{code:6, label:'A/A N+1', long:'Active/Active · N+1 in each of two sites (2N+2)',mult:n=>n,              add:2, live:n=>2*n},
  nndr:{code:4, label:'N+N+DR',  long:'N+N + DR · active/active twin sites (4N)',       mult:n=>3*n,            add:0, live:n=>2*n},
};
const DEFAULTS = {"mfu": 0.5, "mbu": 0.65, "ic": 0.85, "ovh": 30};
const FIELDS = {inBatch:{max:512}};   // the one field solvePool reads

/*ENGINE-START*/
function compute(s){
  const bw = s.bytesW, bk = s.bytesK;
  const weights = s.params * bw;
  const effSeq = s.resident + (s.extend ? s.reasonTok : 0);
  // KV per token. Models that mix full-attention layers with sliding-window
  // layers cost far less per token than their raw head geometry suggests: the
  // window layers only ever hold `kvWin` tokens, so their share shrinks as the
  // sequence grows. kvGlobal/kvWin absent = the classic uniform-attention form.
  const kvL = Math.max(1, s.kvLayers || s.layers);
  const kvGlobal = Math.min(kvL, Math.max(0, s.kvGlobal||0));
  const kvWin = Math.max(0, s.kvWin||0);
  const kvTok = (kvGlobal>0 && kvWin>0)
    ? ( kvGlobal * (s.kvgKeyOnly?1:2) * (s.kvgHeads||s.kvHeads) * (s.kvgDim||s.headDim)
        + (kvL-kvGlobal) * 2 * s.kvHeads * s.headDim * Math.min(1, kvWin/Math.max(1,effSeq))
      ) * bk / 1e9
    : 2 * kvL * s.kvHeads * s.headDim * bk / 1e9;
  const replicas = Math.max(1, Math.floor(s.gpus / Math.max(s.tp,1)));
  const active = s.policy === 'all' ? s.concurrent
               : Math.min(s.concurrent, s.batch * replicas);
  /* Prefix caching. `cachePct` is the share of the RESIDENT sequence that is
     byte-identical across concurrent requests: a system prompt, a tool schema,
     a few-shot block. A server with automatic prefix caching computes those
     blocks once and reuses them, which has two separate consequences, and the
     model must keep them separate:
       prefill  only the uncached remainder is prefilled, so TTFT scales down
       memory   the shared blocks are stored ONCE per replica, not once per
                admitted request
     Decode is deliberately NOT discounted: every request still attends over its
     whole context each step, so the per-step read stays effSeq. Shared-prefix
     (cascade) attention kernels can beat that; treating it as free here would
     make the estimate optimistic, and this tool errs the other way. */
  const cacheFrac = Math.min(0.95, Math.max(0, s.cachePct || 0));
  const cachedTok = Math.floor(s.resident * cacheFrac);
  const uniqueSeq = Math.max(0, effSeq - cachedTok);
  const kvShared = cachedTok * kvTok;
  const kvTotal = active * uniqueSeq * kvTok + replicas * kvShared;
  const act = Math.min(effSeq, 8192) * s.hidden * 12 * bw / 1e9;
  /* NCCL buffers live in a communicator, and a communicator is one tensor-parallel
     replica. Charging (poolGPUs - 1) billed independent replicas for talking to
     each other: 40 TP1 replicas paid 585 GB to communicate with nobody. */
  const fixed = 5, multi = replicas * Math.max(0, Math.max(s.tp,1) - 1) * (s.multiGb != null ? s.multiGb : 15);
  const weightsAll = replicas * weights, actAll = replicas * act;
  const total = weightsAll + kvTotal + actAll + fixed + multi;
  const servingGpus = replicas * Math.max(s.tp,1), idleGpus = s.gpus - servingGpus;
  const avail = servingGpus * s.gpuVram;
  const bwEff = s.gpuBw * s.tp * s.ic * s.mbu * 1000;
  const batchPerRep = Math.max(1, active / replicas);
  const tps = bwEff / (s.active * bw + batchPerRep * effSeq * kvTok);
  const agg = tps * active;
  const prefillTok = Math.max(0, s.resident - cachedTok);
  const ttft = 2 * prefillTok * s.active / (s.gpuTflops * s.tp * s.mfu);
  const itl = 1000 / tps;
  const genTok = s.reasonTok + s.visibleOut;
  const latency = (ttft + s.ovh) / 1000 + genTok / tps;
  const p95 = latency * 1.3;
  // one more admitted call costs only its UNIQUE tokens once the prefix is shared
  const maxBatchMem = Math.max(0, Math.floor((avail - weightsAll - actAll - fixed - multi - replicas*kvShared) / (uniqueSeq * kvTok || 1e-9) / replicas)) || 0;
  const kvDelta = uniqueSeq * kvTok;
  const allActiveVram = weightsAll + s.concurrent * uniqueSeq * kvTok + replicas * kvShared + actAll + fixed + multi;
  const queued = Math.max(0, s.concurrent - active);
  const fits = total <= avail;
  const slo = {
    ttft: s.sloTtft > 0 ? {on:true, pass: ttft <= s.sloTtft} : {on:false, pass:true},
    tps:  s.sloTps  > 0 ? {on:true, pass: tps  >= s.sloTps } : {on:false, pass:true},
    p95:  s.sloP95  > 0 ? {on:true, pass: p95  <= s.sloP95 } : {on:false, pass:true},
  };
  const sloAll = slo.ttft.pass && slo.tps.pass && slo.p95.pass;
  return {weights,weightsAll,kvTok,effSeq,uniqueSeq,cachedTok,kvShared,prefillTok,
          replicas,active,kvTotal,act,actAll,fixed,multi,total,avail,
          servingGpus,idleGpus,bwEff,batchPerRep,tps,agg,ttft,itl,latency,p95,genTok,maxBatchMem,kvDelta,
          allActiveVram,queued,fits,slo,sloAll,headroom:avail-total};
}
/*ENGINE-END*/

/* ---- the studio solver, verbatim ---- */
function solvePool(s){
  const weights=s.params*s.bytesW;
  const actGB=Math.min(s.resident+(s.extend?s.reasonTok:0),8192)*s.hidden*12*s.bytesW/1e9;
  const packPct=Math.min(95,Math.max(50,+($('autoUtil')&&$('autoUtil').value)||80)), pack=packPct/100;
  /* The smallest width that holds one copy with cache room. Use the SAME
     inequality compute() enforces - fixed 5 GB plus (gpus-1) x multiGb across
     the group - instead of charging the multi-GPU overhead to every card, which
     was stricter than the engine and bought a width nobody needed. */
  const mgb=(s.multiGb!=null? s.multiGb : 15);
  /* the shared prefix is resident once per replica whether or not any call is
     in flight, so it belongs in the width that must hold one copy */
  const cacheF=Math.min(0.95,Math.max(0,s.cachePct||0));
  const kvTokFit=(()=>{ try{ return compute({...s, gpus:Math.max(1,s.tp||1), tp:Math.max(1,s.tp||1),
    workers:1, batch:1, concurrent:1}).kvTok; }catch(e){ return 0; } })();
  const sharedGB=Math.floor(s.resident*cacheF)*kvTokFit;
  let tp=[1,2,4,8,16,32,64,72].find(t=>weights+actGB+sharedGB+5+(t-1)*mgb <= pack*s.gpuVram*t);
  if(!tp) return {ok:false, packPct,
    reason:`No TP up to 64 fits one copy of ${s.model.name} on ${s.gpu.name}: quantize the weights or pick a higher-VRAM GPU`};
  const tpFit=tp;
  // each member is one request class: its OWN prefill length, its OWN hidden +
  // visible tokens, its OWN targets. A pooled state only blends these for
  // memory and mix decode-step math; constraints must never cross members
  // (a chatbot's P95 must not pay for a reasoning agent's thinking tokens,
  // a translation TTFT must not pay for a legal doc's 131K prefill).
  // Batch is free until memory or bandwidth says otherwise: an arbitrary cap
  // forces ceil(concurrent/cap) replicas, and every extra replica re-reads the
  // whole weight matrix each decode step. Use the same ceiling the user can set
  // by hand and let the fit and SLO loops find the real limit.
  const BATCH_MAX=(FIELDS.inBatch&&FIELDS.inBatch.max)||512;
  const members = (s.members&&s.members.length? s.members
    : [{name:null, conc:s.concurrent, resident:s.resident, visibleOut:s.visibleOut,
        reasonTok:s.reasonTok, extend:s.extend, sloTtft:s.sloTtft, sloTps:s.sloTps, sloP95:s.sloP95}])
    .map(m=>({...m, gen:(m.reasonTok||0)+(m.visibleOut||0)}));
  // prefill skips the member's cached prefix, exactly as the engine does
  const prefillOf=m=>Math.max(0, m.resident - Math.floor(m.resident*Math.min(0.95,Math.max(0,m.cachePct||0))));
  const ttftOf=(m,t,tflops)=>2*prefillOf(m)*s.active/((tflops||s.gpuTflops)*t*s.mfu);
  // widen TP while any member's OWN TTFT target is missed at its OWN prefill
  /* Widen for the first-token targets, but never past the width that meets them
     or past the node's own NVLink island: an unreachable TTFT used to run this
     loop to TP64 and buy 64 cards per replica for a target still missed. */
  { const wall=64;          // crossing nodes for prefill is allowed; it is priced by ic
    let t=tp;
    while(t<wall && members.some(m=>m.sloTtft>0 && ttftOf(m,t)>m.sloTtft)) t*=2;
    // if even the widest allowed group misses every one of them, the target is
    // not a width problem: keep the fitting width and report it as stuck below
    if(t>tp && members.every(m=>!(m.sloTtft>0) || ttftOf(m,t)>m.sloTtft)) t=tp;
    tp=Math.min(72,t); }
  const ttftTp=tp;                 // the width the first-token targets alone needed
  const widened=tp>tpFit;
  const ttftBinder=widened? (members.filter(m=>m.sloTtft>0).sort((a,b)=>ttftOf(b,1)/b.sloTtft-ttftOf(a,1)/a.sloTtft)[0]||{}).name : null;
  const interactive=members.some(m=>m.sloTtft>0||m.sloTps>0||m.sloP95>0);
  // member latency at the pool's mix decode speed: same step rate for every
  // co-batched request, but each member only decodes its own gen tokens
  const memberP95=(m,mixTps,tpAt,tflops)=>1.3*((ttftOf(m,tpAt,tflops)+s.ovh)/1000 + m.gen/Math.max(1e-6,mixTps));
  /* Plan the pool at one tensor-parallel width. Decode is memory-bandwidth
     bound and bandwidth scales with TP, so for a pool that misses a speed or
     P95 target TP is often far cheaper than replicas: adding replicas only
     pushes batch-per-replica toward 1, which asymptotes, while a wider TP
     raises the ceiling itself. We plan at several widths and buy the cheapest
     one that meets every member's targets. */
  function planAt(tp){
    const crossed=tp>s.perW;
    const ic=crossed? Math.min(s.ic,0.7) : s.ic;
    // A pool owns CARDS, not whole nodes. Pools pack onto shared nodes further
    // down, so rounding each pool up to a full node bought GPUs nobody asked
    // for: a pool needing two cards was handed eight.
    const REP_CAP=Math.max(1, Math.floor(64*s.perW/tp));
    const eva=(reps,batch)=>compute({...s, tp, ic, workers:Math.ceil(reps*tp/s.perW),
      gpus:reps*tp, batch});
    let reps, batch, d;
    let converged=false, sloStuck=null, grewForSlo=0, scaleStuck=false, aloneStuck=false;
    const can={};
    if(interactive){
      // fewest replicas that admit the peak concurrency, then grow until it fits
      reps=Math.max(1, Math.ceil(s.concurrent/BATCH_MAX));
      for(;;){
        batch=Math.min(BATCH_MAX,Math.max(1,Math.ceil(s.concurrent/reps)));
        d=eva(reps,batch);
        if(d.total<=pack*d.avail){ converged=true; break; }
        if(reps>=REP_CAP) break;
        reps++;
      }
      if(converged){
        // what a call gets alone at batch 1 on THIS width (the physical best
        // case here): a target that fails even there cannot be met by more
        // replicas, so we never buy nodes for it at this width
        members.forEach(m=>{
          const alone=compute({...s, resident:m.resident, visibleOut:m.visibleOut,
            reasonTok:m.reasonTok, extend:m.extend, sloTtft:m.sloTtft, sloTps:m.sloTps, sloP95:m.sloP95,
            tp, ic, workers:Math.max(1,Math.ceil(tp/s.perW)), gpus:tp, batch:1, concurrent:1});
          can[m.name||'_'] = {tps: !(m.sloTps>0) || alone.slo.tps.pass,
                              p95: !(m.sloP95>0) || alone.slo.p95.pass};
        });
        const stuckList=[];
        members.forEach(m=>{ const c=can[m.name||'_'], tag=m.name?` (${m.name})`:'';
          if(!c.tps) stuckList.push('per-user speed'+tag);
          if(!c.p95) stuckList.push('P95'+tag); });
        // WHICH targets are missed, not just which kinds: a pool mixing a
        // reachable target with an unreachable one of the same kind used to have
        // the hardware that met the reachable one handed straight back
        const missOf=dd=>{ let t=false,p=false; const who=[];
          members.forEach(m=>{ const c=can[m.name||'_'], id=m.name||'_';
            if(c.tps && m.sloTps>0 && dd.tps < m.sloTps){ t=true; who.push(id+'|tps'); }
            if(c.p95 && m.sloP95>0 && memberP95(m, dd.tps, tp) > m.sloP95){ p=true; who.push(id+'|p95'); } });
          return {t, p, set:who.sort().join(',')}; };
        const r0=reps, b0=batch;
        // How many replicas does the binding target actually need? Decode is
        // bwEff / (activeParams x bytesW + batchPerRep x effSeq x kvTok) and
        // batchPerRep is concurrent/replicas, so the answer is closed form.
        // Growing one replica at a time made a 400-iteration guard the real
        // ceiling: the loop fell out of it holding 400 extra replicas, still
        // missing the target, and reported no problem. Solve it instead.
        const batchFor=r=>Math.min(BATCH_MAX,Math.max(1,Math.ceil(s.concurrent/r)));
        d=eva(reps,batch);
        const miss0=missOf(d);
        if(miss0.t||miss0.p){
          // every per-user speed each target implies, in tok/s
          const needs=[];
          members.forEach(m=>{ const c=can[m.name||'_'];
            if(c.tps && m.sloTps>0) needs.push(m.sloTps);
            if(c.p95 && m.sloP95>0 && m.gen>0){
              const room=m.sloP95/1.3-(ttftOf(m,tp)+s.ovh)/1000;
              needs.push(room>0? m.gen/room : Infinity); } });
          // replicas that speed needs: batch per replica is concurrent/replicas,
          // and below one batch no replica count can help
          // decode reads the whole context per step, so the SPEED term keeps effSeq
          const repsFor=T=>{ const bpr=(d.bwEff/T - s.active*s.bytesW)/Math.max(1e-12, d.effSeq*d.kvTok);
            return bpr>=1? Math.max(r0, Math.ceil(s.concurrent/bpr)) : Infinity; };
          // grow to the strictest target the hardware can still reach. One
          // unreachable target must not suppress growth for a reachable one.
          let want=0;
          needs.forEach(T=>{ if(!isFinite(T)) return; const r2=repsFor(T);
            if(r2<=REP_CAP && r2>want) want=r2; });
          if(want>r0){
            reps=want; batch=batchFor(reps); d=eva(reps,batch);
            // rounding safety net only: the closed form lands on the answer, so
            // stop the moment an extra replica stops shrinking the missed set
            // instead of spending the whole allowance on a target it cannot fix
            for(let guard=0; guard<8 && (missOf(d).t||missOf(d).p) && reps<REP_CAP; guard++){
              const before=missOf(d).set;
              const r2=reps+1, b2=batchFor(r2), d2=eva(r2,b2);
              if(missOf(d2).set===before) break;
              reps=r2; batch=b2; d=d2; }
          }
          const miss=missOf(d);
          if(miss.t||miss.p){
            // stuck at SCALE, not alone at batch 1: name it that way downstream
            if(miss.t) stuckList.push('per-user speed'), scaleStuck=true;
            if(miss.p) stuckList.push('P95'), scaleStuck=true;
            // replicas that fixed nothing are pure waste: give them back. The old
            // one-at-a-time loop ran into its 400-iteration guard, kept all 400 and
            // reported no problem at all. The comparison must be the SET of missed
            // targets: growth that met one of them has earned its hardware.
            if(miss.set===miss0.set){ reps=r0; batch=b0; d=eva(reps,batch); }
          }
        }
        // Give back what the targets do not need. Worker granularity can hand a
        // small pool a whole node, and every surplus replica re-reads the full
        // weights each decode step, so shrinking raises utilization AND speed
        // per card. Stop the moment memory or any member's target says no.
        for(let guard=0; guard<400 && reps>1; guard++){
          const r2=reps-1;
          const b2=Math.min(BATCH_MAX,Math.max(1,Math.ceil(s.concurrent/r2)));
          const d2=eva(r2,b2);
          if(d2.total>pack*d2.avail) break;
          if(d2.queued>0) break;                    // must still admit the peak
          const m2=missOf(d2); if(m2.t||m2.p) break;
          reps=r2; batch=b2; d=d2;
        }
        sloStuck = stuckList.length? [...new Set(stuckList)].join(' and ') : null;
        // a target that fails alone at batch 1 can never be met; one that only
        // fails at this concurrency needs more replicas than the fleet allows.
        // Saying "fails even alone at batch 1" about the second is simply false.
        aloneStuck = members.some(m=>{ const c=can[m.name||'_']; return !c.tps || !c.p95; });
        grewForSlo=Math.max(0, reps-r0);
      }
    } else {
      // offline: queueing is fine, so keep hardware minimal and pick the largest batch that fits
      reps=1;
      outer: for(;;){
        for(const b of [512,256,128,64,32,16,8,4,2,1]){
          batch=b; d=eva(reps,b);
          if(d.total<=pack*d.avail){ converged=true; break outer; }
        }
        if(reps>=REP_CAP) break;
        reps++;
      }
    }
    return {tp, crossed, ic, batch, d, converged, sloStuck, grewForSlo, can, scaleStuck, aloneStuck,
      replicas:reps, cards:reps*tp,
      workers:Math.max(1,Math.ceil(reps*tp/s.perW)),
      physGpus: reps*tp};
  }
  // TP candidates: the TTFT-driven width, plus wider ones up to one node's
  // NVLink island (crossing nodes costs interconnect efficiency, so we never
  // widen past perW purely for speed).
  /* Candidate widths. A wider group is not only a speed lever: it also holds a
     bigger batch per replica, so a pool with NO speed target at all can still
     need far fewer cards at TP4 than at TP1. Gating the sweep on speed targets
     gave memory-bound pools an explosion of narrow replicas. */
  const cands=[tp];
  if(interactive||s.concurrent>1) [1,2,4,8,16,32,64,72].forEach(t=>{ if(t>tp&&t<=s.perW) cands.push(t); });
  let plan=null;
  cands.forEach(t=>{ const pl=planAt(t); if(!pl.converged) return;
    const better = !plan
      || (!pl.sloStuck && plan.sloStuck)
      || (!!pl.sloStuck===!!plan.sloStuck && pl.physGpus < plan.physGpus - 1e-9);
    if(better) plan=pl; });
  if(!plan) plan=planAt(tp);
  const tpWide=plan.tp>tp;
  tp=plan.tp;
  const crossed=plan.crossed, ic=plan.ic;
  let workers=plan.workers, batch=plan.batch, d=plan.d;
  const cards=plan.cards;
  const converged=plan.converged, sloStuck=plan.sloStuck, grewForSlo=plan.grewForSlo;
  members.forEach(m=>{ const c=plan.can[m.name||'_']||{}; m.tpsCan=c.tps!==false; m.p95Can=c.p95!==false; });
  const tpsCan=members.every(m=>m.tpsCan), p95Can=members.every(m=>m.p95Can);
  if(!converged) return {ok:false, packPct,
    reason:`Could not fit ${s.model.name} at TP${tp} within the ${packPct}% memory target even at 64 workers: quantize the weights, raise the target, or pick a higher-VRAM GPU`};
  // A dedicated pool costs CARDS since 5.21 (it packs onto shared nodes), so
  // physGpus must be that same number. Pricing it in whole nodes made the sliced
  // branch below beat a plan that was already cheaper: 3 MIG slices "saved"
  // hardware against a single card rounded up to a node of eight.
  const dedicated={ok:true, mode:'dedicated', tp, tpFit, widened, ttftBinder, ttftTp, crossed, workers, cards, batch, packPct, weights, actGB, sloStuck, grewForSlo,
    physGpus: cards};
  // MIG-sliced alternative: TP1 pools whose copy fits a hardware slice can run
  // one replica per slice, sharing physical GPUs with other models/supports
  if(tp===1 && interactive && UC.length>1){
    const profs=sliceProfiles(s.gpu);
    // honest pricing: slices only exist whole, so cost = first-fit-decreasing
    // bins of part.max units. Supports already occupy shared bins; the sliced
    // pool's marginal cost is (bins with pool slices) - (bins with supports alone).
    const binCount=(unitsArr, max)=>{ const bins=[];
      unitsArr.slice().sort((a,b)=>b-a).forEach(u2=>{ const i2=bins.findIndex(x=>x+u2<=max);
        if(i2<0) bins.push(u2); else bins[i2]+=u2; });
      return bins.length; };
    const partS=s.gpu.part||{};
    let supU=[];
    try{ allocSupports({g:s.gpu}).layout.forEach(b=>b.slices.forEach(sl=>{ if(sl.n>0) supU.push(sliceCost(partS, sl.n)); })); }catch(e){}
    const supAlone=supU.length? binCount(supU, binCap(partS)) : 0;
    // why (per largest profile examined) slicing was rejected: surfaced in the
    // auto-size narrative so a half-empty dedicated GPU never looks arbitrary
    let best=null, why=profs.length? null : {t:'nopart'};
    for(const prof of profs){
      if(weights+actGB+1.4 > pack*prof.gb){ why={t:'fit', need:weights+actGB+1.4, cap:pack*prof.gb}; continue; }
      const syn={...s, gpuVram:prof.gb, gpuBw:prof.bw, gpuTflops:prof.tflops, tp:1, perW:1, ic:1, multiGb:1.4};
      // a slice that cannot meet a target the dedicated plan CAN meet is out;
      // targets unachievable on any hardware are ignored here too (parity with
      // the dedicated path). All checks are PER MEMBER with that member's own
      // request shape, never the blended pool shape.
      let rejected=null;
      for(const m of members){
        if(m.sloTtft>0 && ttftOf(m,1,prof.tflops) > m.sloTtft && !(ttftOf(m,tp) > m.sloTtft)){
          rejected={t:'ttft', ms:ttftOf(m,1,prof.tflops), who:m.name}; break; }
        const aloneM=compute({...syn, resident:m.resident, visibleOut:m.visibleOut,
          reasonTok:m.reasonTok, extend:m.extend, sloTtft:m.sloTtft, sloTps:m.sloTps, sloP95:m.sloP95,
          gpus:1, workers:1, batch:1, concurrent:1});
        if(m.sloTps>0 && m.tpsCan!==false && !aloneM.slo.tps.pass){
          rejected={t:'slo', m:'per-user speed'+(m.name?` (${m.name})`:''), have:fmt(aloneM.tps)+' tok/s', want:fmt(m.sloTps)+' tok/s'}; break; }
        if(m.sloP95>0 && m.p95Can!==false && !aloneM.slo.p95.pass){
          rejected={t:'slo', m:'P95 latency'+(m.name?` (${m.name})`:''), have:fmt(aloneM.p95)+' s', want:fmt(m.sloP95)+' s'}; break; }
      }
      if(rejected){ why=rejected; continue; }
      const SLICE_CAP=64;
      let slices=Math.max(1,Math.ceil(s.concurrent/SLICE_CAP)), sb=0, sd=null, okFit=false, stuck=null;
      for(let guard=0; guard<200; guard++){
        sb=Math.min(BATCH_MAX,Math.max(1,Math.ceil(s.concurrent/slices)));
        sd=compute({...syn, gpus:slices, workers:slices, batch:sb});
        if(sd.total<=pack*sd.avail){ okFit=true; break; }
        if(slices>=SLICE_CAP) break;
        slices++;
      }
      if(!okFit){ why={t:'kv'}; continue; }
      const missSlice=dd=>{ let t=false,p=false;
        members.forEach(m=>{
          if(m.tpsCan!==false && m.sloTps>0 && dd.tps < m.sloTps) t=true;
          if(m.p95Can!==false && m.sloP95>0 && memberP95(m, dd.tps, 1, prof.tflops) > m.sloP95) p=true; });
        return {t,p}; };
      for(let guard=0; guard<200; guard++){
        const miss=missSlice(sd);
        if(!(miss.t||miss.p)) break;
        if(sb<=1 || slices>=SLICE_CAP){ stuck=(miss.t?'per-user speed':'')+(miss.t&&miss.p?' and ':'')+(miss.p?'P95':''); break; }
        slices++;
        sb=Math.min(BATCH_MAX,Math.max(1,Math.ceil(s.concurrent/slices)));
        sd=compute({...syn, gpus:slices, workers:slices, batch:sb});
      }
      if(stuck){ why={t:'stuck', stuck}; continue; }
      const packed=binCount([...Array(slices).fill(sliceCost(partS, prof.units)), ...supU], binCap(partS));
      const phys=Math.max(0, packed-supAlone);
      if(!best || phys<best.physGpus) best={ok:true, mode:'sliced', tp:1, sliceU:prof.units, prof,
        workers:slices, batch:sb, packPct, weights, actGB, physGpus:phys, sloStuck:null, grewForSlo:0, widened:false, crossed:false, tpFit:1};
    }
    // pick sliced only when it genuinely saves hardware; targets no hardware can
    // meet are missed identically on both paths and carry over to the report
    if(best){
      best.sloStuck=[...new Set(members.flatMap(m=>[m.tpsCan===false?'per-user speed'+(m.name?` (${m.name})`:''):null,
        m.p95Can===false?'P95'+(m.name?` (${m.name})`:''):null]).filter(Boolean))].join(' and ')||null;
      if(best.physGpus < dedicated.cards - 0.01) return best;
      why={t:'nosave', phys:best.physGpus, ded:dedicated.cards};
    }
    dedicated.sliceWhy =
      !why? null
      : why.t==='nopart'? `${s.gpu.name} has no isolated partitioning (MIG), so each replica keeps a whole GPU`
      : why.t==='fit'? `its ${fmt(why.need)} GB copy does not fit even the largest slice (${fmt(why.cap)} GB usable at the ${packPct}% memory target)`
      : why.t==='slo'? `even alone on the largest usable slice, ${why.m} reaches ${why.have} against the ${why.want} target`
      : why.t==='ttft'? `a slice's reduced compute cannot meet the ${fmt(s.sloTtft)} ms TTFT target (${fmt(why.ms)} ms prefill on the largest usable slice)`
      : why.t==='stuck'? `slices cannot meet the ${why.stuck} target at any replica count`
      : why.t==='kv'? `the KV cache does not fit slice memory at any replica count`
      : why.t==='nosave'? `sharing would not reduce hardware (${fmt(why.phys)} shared-GPU equivalents vs ${why.ded} dedicated GPUs)`
      : null;
  }
  return dedicated;
}

/* ---- helpers ---- */
const fmt = x => !isFinite(x) ? '-' : Math.abs(x)>=1000 ? Math.round(x).toLocaleString('en-US') : Math.abs(x)>=100 ? x.toFixed(0) : Math.abs(x)>=10 ? x.toFixed(1) : x.toFixed(2).replace(/\.00$/,'');
const fmtTok = x => x>=1048576 ? (x/1048576)+'M' : x>=1024 ? Math.round(x/1024)+'K' : String(x);
const findBy = (arr, q) => arr.find(x=>x.name.toLowerCase()===q.toLowerCase()) || arr.find(x=>x.name.toLowerCase().includes(q.toLowerCase()));

/* ---- shims so the studio's solvePool runs verbatim outside the page ----
   UC.length 1 keeps the MIG-sliced branch off (the CLI sizes one dedicated
   pool); $('autoUtil') carries the --target value; the slice helpers are only
   reachable from that gated branch. */
let __target = 80;
const $ = id => id==='autoUtil' ? {value:__target} : null;
const UC = {length:1};
const sliceProfiles = () => [];
const allocSupports = () => ({layout:[]});
const binCap = () => 8;
const sliceCost = (p,u) => u;

function makeState(o){
  const m = o.model, g = o.gpu;
  return {
    model:m, gpu:g, wq:o.wq, kq:o.kq,
    params:m.params, active:m.active, hidden:m.hidden, layers:m.layers,
    kvHeads:m.kvHeads, headDim:m.headDim, ctx:m.ctx,
    kvGlobal:m.kvGlobal, kvWin:m.kvWin, kvgHeads:m.kvgHeads, kvgDim:m.kvgDim,
    kvgKeyOnly:m.kvgKeyOnly, kvLayers:m.kvLayers,
    bytesW:o.wq.bytes, bytesK:o.kq.bytes,
    resident:o.resident, visibleOut:o.visibleOut, reasonTok:o.reasonTok, extend:o.extend!==false,
    cachePct:o.cachePct??0,
    concurrent:o.concurrent, batch:o.batch, policy:o.policy||'running',
    workers:o.workers, perW:o.perW, gpus:o.gpus??(o.workers*o.perW), tp:Math.min(o.tp, o.gpus??(o.workers*o.perW)),
    gpuVram:g.vram, gpuBw:g.bw, gpuTflops:g.tflops,
    mfu:o.mfu??DEFAULTS.mfu, mbu:o.mbu??DEFAULTS.mbu,
    ic:o.ic??((o.tp||1)>o.perW? Math.min(DEFAULTS.ic,0.7) : DEFAULTS.ic), ovh:o.ovh??DEFAULTS.ovh,
    sloTtft:o.sloTtft??0, sloTps:o.sloTps??0, sloP95:o.sloP95??0,
  };
}

/* the studio auto-sizer, not a port of it: solvePool above IS the studio's */
function autoSolve(o){
  __target = Math.min(95, Math.max(50, o.target??80));
  const s0 = makeState({...o, workers:1, tp:1, batch:o.batch??64});
  const r = solvePool(s0);
  if(!r.ok) return {error:r.reason};
  const ic = r.tp>o.perW ? Math.min(s0.ic,0.7) : s0.ic;
  const s = makeState({...o, workers:r.workers, tp:r.tp, batch:r.batch, gpus:r.cards, ic});
  return {tp:r.tp, workers:r.workers, cards:r.cards, batch:r.batch,
    widened:!!r.widened, sloStuck:r.sloStuck||null, d:compute(s), s};
}

function story(s,d){
  const m=s.model, g=s.gpu, L=[];
  const minGpus=Math.ceil((d.weights+d.act)/s.gpuVram);
  L.push(`One copy of ${m.name} at ${s.wq.name} weighs ${fmt(d.weights)} GB (${fmt(s.params)}B params x ${s.bytesW} B). A ${g.name} holds ${fmt(s.gpuVram)} GB, so one copy needs at least ${minGpus} GPU(s); it is sliced across TP${s.tp} (${fmt(s.tp*s.gpuVram)} GB per group).`);
  if(d.replicas>1) L.push(`Serving ${s.concurrent} concurrent calls at batch ${s.batch} takes ${d.replicas} full copies: ${d.replicas} x TP${s.tp} = ${d.servingGpus} serving GPUs${d.queued>0?` (${d.queued} calls queue at peak)`:''}. The model alone needed ${minGpus}; the rest serve concurrency.`);
  else L.push(`One copy serves everything: batch ${s.batch} admits ${d.active} of ${s.concurrent} calls${d.queued>0?`, ${d.queued} queue`:''}.`);
  const hyb=(s.kvGlobal>0&&s.kvWin>0);
  L.push(`KV cache: ${(d.kvTok*1e6).toFixed(1)} KB/token at ${s.kq.name}${hyb?` (hybrid attention: ${s.kvGlobal} of ${s.kvLayers||s.layers} layers hold the full context, the rest a ${fmtTok(s.kvWin)}-token window, so the per-token cost falls as context grows)`:''}; ${fmt(d.effSeq*d.kvTok)} GB per admitted ${fmtTok(d.effSeq)}-token conversation; ${fmt(d.kvTotal)} GB total across ${d.active} admitted.`);
  L.push(`Envelope: TTFT ~${fmt(d.ttft)} ms, ~${fmt(d.tps)} tok/s per user, aggregate ~${fmt(d.agg)} tok/s, mean latency ${fmt(d.latency)} s (P95 ~${fmt(d.p95)} s).`);
  return L;
}

function report(s,d,resil,sol,o0){
  o0 = o0 || {};
  const info=RESIL[resil||'n']||RESIL.n;
  const servW=Math.max(1,Math.ceil(d.servingGpus/s.perW));
  const resilW=info.mult(servW)+info.add;
  const procW=servW+resilW, procG=procW*s.perW;
  const out={
    fits:d.fits, utilizationPct:+(d.total/d.avail*100).toFixed(1),
    memory:{ totalGB:+d.total.toFixed(1), availGB:d.avail, weightsPerReplicaGB:+d.weights.toFixed(1),
      weightsAllGB:+d.weightsAll.toFixed(1), kvTotalGB:+d.kvTotal.toFixed(1), replicas:d.replicas,
      kvPerTokenKB:+(d.kvTok*1e6).toFixed(2), headroomGB:+d.headroom.toFixed(1),
      sharedPrefixPct:+(Math.min(0.95,Math.max(0,s.cachePct||0))*100).toFixed(0),
      residentFromCall: o0.session? `${o0.session.mins} min x ${o0.session.tokMin||o0.session.rate} tok/min + ${o0.session.base} base (${o0.session.basis})` : undefined,
      cachedPrefixTok:d.cachedTok, uniqueSeqTok:d.uniqueSeq,
      kvSharedPerReplicaGB:+d.kvShared.toFixed(2) },
    fleet:{ servingCards:d.servingGpus, nodes:servW, gpusPerNode:s.perW, tp:s.tp,
      batchPerReplica:s.batch, admitted:d.active, queued:d.queued },
    performance:{ ttftMs:+d.ttft.toFixed(1), prefilledTok:d.prefillTok, perUserTps:+d.tps.toFixed(1), aggregateTps:+d.agg.toFixed(0),
      meanLatencyS:+d.latency.toFixed(2), p95S:+d.p95.toFixed(2) },
    slo:{ ttft:s.sloTtft? (d.slo.ttft.pass?'PASS':'FAIL'):'off', tps:s.sloTps? (d.slo.tps.pass?'PASS':'FAIL'):'off',
      p95:s.sloP95? (d.slo.p95.pass?'PASS':'FAIL'):'off' },
    resilience:{ model:info.long, procuredNodes:procW, procuredGpus:procG, powerKwTdp:+(procG*s.gpu.watts/1000).toFixed(1),
      degradedOnSiteLoss:!!info.degraded },
    story: story(s,d),
    caveat:'Peak estimates; production typically achieves 70-90%. Validate with vLLM bench / GenAI-Perf. Interactive studio: https://gpuscale.net',
  };
  if(sol&&sol.sloStuck) out.sloStuck=sol.sloStuck+' target not achievable at this concurrency on this hardware';
  return out;
}

/* ---- CLI ---- */
const args={}; const argv=process.argv.slice(2);
for(let i=0;i<argv.length;i++){ const a=argv[i];
  if(a.startsWith('--')){ const k=a.slice(2); const v=(argv[i+1]&&!argv[i+1].startsWith('--'))?argv[++i]:true; args[k]=v; } }

if(args['list-models']){ MODELS.forEach(m=>console.log(`${m.name}  · ${m.params}B total / ${m.active}B active · ctx ${fmtTok(m.ctx)} · ${m.arch}`)); process.exit(0); }
if(args['list-gpus']){ GPUS.forEach(g=>console.log(`${g.name}  · ${g.vram} GB · ${g.bw} TB/s · ${g.tflops} dense FP16 TF · ${g.watts} W`)); process.exit(0); }
if(args['list-workloads']){ CASES.forEach(c=>console.log(`${c.name}  · ctx ${fmtTok(c.resident||0)} · out ${c.visibleOut} · reasoning ${c.reasoning}${c.reasonTok?' ('+c.reasonTok+' tok)':''} · SLO ${c.ttftTarget}ms/${c.tpsTarget}tps/${c.p95Target}s${c.policy==='all'?' · KV pinned per session':''}`)); process.exit(0); }
if(args.help||Object.keys(args).length===0){
  console.log(`GPUscale sizing CLI (engine v${META.engine}, library ${META.library}, studio ${META.studio})
Usage:
  sizing.mjs --model "DeepSeek-V3" --gpu B300 --quant FP8 [--kv FP8]
             (--workload "Internal GPT" | --resident 16384 --out 800 --reasoning 0)
             --concurrent 377 [--auto [--target 80] | --workers 3 --tp 4 --batch 63]
             [--ttft ms --tps tokps --p95 s] [--policy running|all] [--cache pct]
             [--call-minutes m [--tok-min r --prompt-tok t --basis peak|mean]]
             [--perw 8] [--resilience n|n1|n2|nn|dr|drh|aa|aas|aas1|aass|aan1|nndr] [--json]
  sizing.mjs --list-models | --list-gpus | --list-workloads`);
  process.exit(0);
}

const model=findBy(MODELS, String(args.model||''));
if(!model){ console.error('Unknown model. Try --list-models'); process.exit(1); }
const gpu=findBy(GPUS, String(args.gpu||'H100 80GB SXM'));
if(!gpu){ console.error('Unknown GPU. Try --list-gpus'); process.exit(1); }
const wq=QUANTS.find(q=>q.name.toLowerCase()===String(args.quant||'FP8').toLowerCase())||QUANTS.find(q=>q.name==='FP8');
const kq=KV_QUANTS.find(q=>q.name.toLowerCase()===String(args.kv||'FP8').toLowerCase())||KV_QUANTS.find(q=>q.name==='FP8');

let wl={resident:4096, visibleOut:400, reasonTok:0, sloTtft:0, sloTps:0, sloP95:0, policy:'running', cachePct:0};
if(args.workload){
  const c=CASES.find(x=>x.name.toLowerCase().includes(String(args.workload).toLowerCase()));
  if(c) wl={resident:c.resident||4096, visibleOut:c.visibleOut||400,
            reasonTok:c.reasonTok!=null? c.reasonTok : (REASON_TOK[c.reasoning]||0),
            sloTtft:c.ttftTarget||0, sloTps:c.tpsTarget||0, sloP95:c.p95Target||0,
            policy:c.policy==='all'?'all':'running', cachePct:(c.cachePct||0)/100};
}
if(args.resident) wl.resident=+args.resident;
if(args.out) wl.visibleOut=+args.out;
if(args.reasoning) wl.reasonTok=+args.reasoning;
if(args.ttft) wl.sloTtft=+args.ttft;
if(args.tps) wl.sloTps=+args.tps;
if(args.p95) wl.sloP95=+args.p95;
if(args.policy) wl.policy=String(args.policy)==='all'?'all':'running';
// share of the resident sequence that is byte-identical on every call and so is
// prefilled once and held once per replica. Default 0: size for a full prefill
// unless the caller states a measured hit rate.
if(args.cache!=null&&args.cache!==true) wl.cachePct=Math.min(0.95,Math.max(0,+args.cache/100||0));
/* --call-minutes: a conversation holds its transcript, so the resident sequence
   grows with the length of the call. Presets that describe a session carry the
   shape their own resident figure was built from, so stating the length alone is
   enough. Matters most when KV is pinned per session. */
if(args['call-minutes']!=null&&args['call-minutes']!==true){
  const mins=Math.min(240,Math.max(0,+args['call-minutes']||0));
  const sh=(args.workload&&CASES.find(x=>x.name.toLowerCase().includes(String(args.workload).toLowerCase()))||{}).session;
  const rate=args['tok-min']!=null? Math.max(0,+args['tok-min']||0) : (sh? sh.tokMin : 200);
  const base=args['prompt-tok']!=null? Math.max(0,+args['prompt-tok']||0) : (sh? sh.base : Math.max(0,wl.resident-1000));
  const half=/^(mean|avg)/i.test(String(args.basis||''));
  if(mins>0&&rate>0){ wl.resident=Math.round(base+rate*mins/(half?2:1)); wl.session={mins,rate,base,basis:half?'mean':'peak'}; }
}

const base={ model, gpu, wq, kq, ...wl, concurrent:+(args.concurrent||64), perW:+(args.perw||8), extend:true };

let s,d,sol=null;
if(args.auto || !(args.workers&&args.tp)){
  sol=autoSolve({...base, target:+(args.target||80)});
  if(sol.error){ console.error(sol.error); process.exit(2); }
  s=sol.s; d=sol.d;
} else {
  s=makeState({...base, workers:+args.workers, tp:+args.tp, batch:+(args.batch||4)});
  d=compute(s);
}
const rep=report(s,d,String(args.resilience||'n'),sol,wl);
if(args.json){ console.log(JSON.stringify(rep,null,2)); }
else {
  console.log(`\n=== ${model.name} · ${wq.name} weights / ${kq.name} KV · ${gpu.name} ===`);
  console.log(`${rep.fits?'FITS':'DOES NOT FIT'} · ${rep.utilizationPct}% of serving memory · ${rep.fleet.servingCards} serving GPUs on ${rep.fleet.nodes} node(s) · ${rep.memory.replicas} replicas x TP${rep.fleet.tp} · batch ${rep.fleet.batchPerReplica}`);
  console.log(`admitted ${rep.fleet.admitted}/${s.concurrent}${rep.fleet.queued?` (queued ${rep.fleet.queued})`:''} · TTFT ${rep.performance.ttftMs} ms · ${rep.performance.perUserTps} tok/s/user · P95 ${rep.performance.p95S} s`);
  console.log(`SLO: TTFT ${rep.slo.ttft} · TPS ${rep.slo.tps} · P95 ${rep.slo.p95}${rep.sloStuck?` · NOTE: ${rep.sloStuck}`:''}`);
  console.log(`resilience ${rep.resilience.model}: ${rep.resilience.procuredNodes} nodes · ${rep.resilience.procuredGpus} GPUs · ~${rep.resilience.powerKwTdp} kW TDP`);
  console.log('');
  rep.story.forEach(p=>console.log('· '+p));
  console.log('\n'+rep.caveat);
}

